In [1]:
import pandas as pd

In [2]:
df_2015 = pd.read_csv('2015_복지_사회참여_문화와여가_소득과소비_노동.csv')
df_2017 = pd.read_csv('2017_복지_사회참여_문화와여가_소득과소비_노동.csv')
df_2019 = pd.read_csv('2019_복지_사회참여_문화와여가_소득과소비_노동.csv')
df_2021 = pd.read_csv('2021_복지_사회참여_문화와여가_소득과소비_노동.csv')
df_2023 = pd.read_csv('2023_복지_사회참여_문화와여가_소득과소비_노동.csv')
df_2017

c:\Users\sanna\miniconda3\envs\myenv\lib\site-packages\IPython\core\interactiveshell.py:3508: DtypeWarning: Columns (185) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\sanna\miniconda3\envs\myenv\lib\site-packages\IPython\core\interactiveshell.py:3508: DtypeWarning: Columns (189) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\sanna\miniconda3\envs\myenv\lib\site-packages\IPython\core\interactiveshell.py:3508: DtypeWarning: Columns (234) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\sanna\miniconda3\envs\myenv\lib\site-packages\IPython\core\interactiveshell.py:3508: DtypeWarning: Columns (236) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,가구일련번호,가구원번호,행정구역시도코드,만연령,성별코드,주관적만족감코드,가구주관계코드,성취만족도코드,교육정도코드,재학상태코드,...,분류코드_자원봉사여부,분류코드_자원봉사정기성여부,분류코드_계층의식코드,분류코드_주관적소득수준코드,분류코드_소득만족도코드,분류코드_고용안전성코드,분류코드_청소년교육정도1코드,분류코드_청소년교육정도2코드,가구가중값,가구원가중값
0,1,1,11,77,1,3,1,3.0,3,1.0,...,C320,NaN,C430,I030,I110,NaN,NaN,NaN,1570.80310,1850.77040
1,1,2,11,73,2,4,2,4.0,3,1.0,...,C320,NaN,C430,NaN,I110,NaN,NaN,NaN,NaN,2023.36980
2,1,3,11,13,1,3,5,NaN,3,2.0,...,C310,C312,C420,NaN,NaN,NaN,T210,T212,NaN,1869.32880
3,10,1,11,73,2,4,1,4.0,2,1.0,...,C320,NaN,C430,I030,I110,NaN,NaN,NaN,2151.41420,2399.75800
4,100,1,11,20,1,2,1,3.0,5,2.0,...,C320,NaN,C420,I020,I110,NaN,T210,T213,1811.29160,1771.32860
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37478,9997,2,32,61,2,2,2,2.0,3,1.0,...,C320,NaN,C420,NaN,I110,NaN,NaN,NaN,NaN,718.64613
37479,9998,1,32,88,1,3,1,3.0,3,1.0,...,C320,NaN,C420,I020,I110,NaN,NaN,NaN,549.40095,491.50610
37480,9998,2,32,88,2,3,2,3.0,1,1.0,...,C320,NaN,C420,NaN,I110,NaN,NaN,NaN,NaN,525.73232
37481,9999,1,32,62,1,3,1,3.0,4,1.0,...,C310,C312,C430,I030,I110,L010,NaN,NaN,608.32842,708.72557
37482,9999,2,32,56,2,3,2,2.0,3,1.0,...,C310,C311,C430,NaN,I110,NaN,NaN,NaN,NaN,648.32508

In [3]:
# 데이터프레임들을 딕셔너리로 묶음
years = {
    "2015": df_2015,
    "2017": df_2017,
    "2019": df_2019,
    "2021": df_2021,
    "2023": df_2023
}

# 각 연도별 피쳐 추출
features = {year: df.columns.tolist() for year, df in years.items()}

# 출력
for year, cols in features.items():
    print(f"{year} features:", cols)

2015 features: ['가구일련번호', '가구원번호', '행정구역시도코드', '만연령', '성별코드', '주관적만족감코드', '가구주관계코드', '교육정도코드', '재학상태코드', '혼인상태코드', '재학학년코드', '장애인복지카드_소유여부', '생활여건변화_전반적생활여건코드', '생활여건변화_보건의료서비스코드', '생활여건변화_사회보장제도코드', '생활여건변화_문화여가생활여건코드', '사회보험료부담인식_건강보험납부여부', '사회보험료부담인식_건강보험부담정도코드', '사회보험료부담인식_국민연금납부여부', '사회보험료부담인식_국민연금부담정도코드', '사회보험료부담인식_고용보험납부여부', '사회보험료부담인식_고용보험부담정도코드', '향후추가대상공공시설_1순위코드', '향후추가대상공공시설_2순위코드', '향후추가대상공공시설_3순위코드', '향후추가대상복지서비스_1순위코드', '향후추가대상복지서비스_2순위코드', '향후추가대상복지서비스_3순위코드', '선호장례방법코드', '사회장애인차별정도코드', '장애인견해코드', '장애인관련시설견해코드', '장애인복지사업견해코드', '우선실시장애인복지사업_1순위코드', '우선실시장애인복지사업_2순위코드', '우선실시장애인복지사업_3순위코드', '노후준비방법_본인노후준비여부', '노후준비방법_주된방법코드', '노후준비방법_부수적방법코드', '노후준비방법_노후미준비사유코드', '노후사회적관심사코드', '노후희망활동코드', '생활비마련방법코드', '생활비마련방법_본인및배우자부담코드', '생활비마련방법_지원자녀및친척동거여부', '현재자녀동거여부', '현재자녀동거사유_1순위코드', '현재자녀동거사유_2순위코드', '현재자녀동거사유_3순위코드', '현재자녀비동거사유_1순위코드', '현재자녀비동거사유_2순위코드', '현재자녀비동거사유_3순위코드', '향후자녀동거의향여부', '향후희망거처코드', '사회적관계망_가사도움요청대상유무', '사회적관계망_가사도움요청대상인원수', '사회적관계망_자금차입도움요청대상유무', '사회적관계망_자금차입도움요청대상인원수', '사회적관계망_대화상대도움요청대상유무', '사회적관계망_대화상대도움요청대상인원수', '단체참여여부', '참여단체_1순위코드', '참여단체_2순위코드', '참여단체_3순위코드', '기부여부', '미기부사유코드', '기부내용_대상자직접후원_현금횟수', '기부내용_대상자직접후원_현금금액', '기부내용_대상자직접후원_물품횟수', '기부내용_언론기관후원_현금횟수', '기부내용_언론기관후원_현금금액', '기부내용_언론기관후원_물품횟수', '기부내용_모금단체후원_현금횟수', '기부내용_모금단체후원_현금금액', '기부내용_물품후원단체후원_물품횟수', '기부내용_종교단체후원_현금횟수', '기부내용_종교단체후원_현금금액', '기부내용_종교단체후원_물품횟수', '기부내용_직장기업후원_현금횟수', '기부내용_직장기업후원_현금금액', '기부내용_직장기업후원_물품횟수', '기부내용_기타_현금횟수', '기부내용_기타_현금금액', '기부내용_기타_물품횟수', '정기기부_현금기부주기코드', '정기기부_물품기부주기코드', '기부희망분야_1순위코드', '기부희망분야_2순위코드', '기부희망분야_3순위코드', '기부대상인지경로코드', '향후기부의사여부', '기부문화확산_1순위코드', '유산기부의사여부', '기부문화확산_2순위코드', '기부문화확산_3순위코드', '자원봉사활동여부', '자원봉사활동_아동청소년노인장애인재소자관련횟수', '자원봉사활동_아동청소년노인장애인재소자관련시간수', '자원봉사활동_환경보전범죄예방관련횟수', '자원봉사활동_환경보전범죄예방관련시간수', '자원봉사활동_자녀교육관련횟수', '자원봉사활동_자녀교육관련시간수', '자원봉사활동_국가및지역행사관련횟수', '자원봉사활동_국가및지역행사관련시간수', '자원봉사활동_재해지역주민돕기및시설복구관련횟수', '자원봉사활동_재해지역주민돕기및시설복구관련시간수', '자원봉사활동_기타일반봉사관련횟수', '자원봉사활동_기타일반봉사관련시간수', '자원봉사활동정기성여부', '자원봉사활동정기성주기코드', '향후자원봉사활동의사여부', '자원봉사활동인지경로코드', '전문성활용자원봉사활동_참석여부', '계층의식코드', '본인세대_계층이동코드', '전문성활용자원봉사활동_내용코드', '자식세대_계층이동코드', '신문_일반신문구독여부', '신문_인터넷신문구독여부', '독서여부', '독서_잡지류권수', '독서_교양서적권수', '독서_직업직무관련서적권수', '독서_생활취미정보서적권수', '독서_기타권수', '문화예술스포츠관람여부', '문화예술스포츠관람_음악연주회횟수', '문화예술스포츠관람_연극마당극뮤지컬횟수', '문화예술스포츠관람_무용횟수', '문화예술스포츠관람_영화횟수', '문화예술스포츠관람_박물관횟수', '문화예술스포츠관람_미술관횟수', '문화예술스포츠관람_스포츠횟수', '레저시설이용횟수', '레저시설_관광명소유적지국립공원이용횟수', '레저시설_온천장스파이용횟수', '레저시설_골프장이용횟수', '레저시설_스키장이용횟수', '레저시설_해수욕장이용횟수', '레저시설_산림욕장휴양림이용횟수', '레저시설_놀이공원이용횟수', '레저시설_수영장워터파크포함이용횟수', '레저시설_기타이용횟수', '국내관광여행경험여부', '국내관광여행_숙박여행횟수', '국내관광여행_숙박여행1회평균숙박일수', '국내관광여행_당일여행횟수', '해외여행경험여부', '해외여행경험_관광횟수', '해외여행경험_가족친지관련횟수', '해외여행경험_업무횟수', '해외여행경험_교육횟수', '과거해외여행경험여부', '주말휴일여가활용_1순위코드', '주말휴일여가활용_2순위코드', '주말휴일여가활용_3순위코드', '여가활동_동반자코드', '여가활용만족도코드', '여가활용불만족사유코드', '향후희망여가활동_1순위코드', '향후희망여가활동_2순위코드', '향후희망여가활동_3순위코드', '주관적소득수준코드', '소득변화코드', '부채변화코드', '내년가구재정상태코드', '긴축소비지출항목_1순위코드', '긴축소비지출항목_2순위코드', '긴축소비지출항목_3순위코드', '현재소득여부', '소득만족도코드', '소비생활만족도코드', '직업선택요인_1순위코드', '직업선택요인_2순위코드', '직업선택요인_3순위코드', '청년선호직장코드', '여성취업견해코드', '여성취업시기코드', '여성취업장애요인_1순위코드', '여성취업장애요인_2순위코드', '여성취업장애요인_3순위코드', '지난1주간경제활동여부', '일가정생활우선도코드', '고용안정성코드', '직장산업대분류코드', '직업대분류코드', '종사상지위코드', '임금근로자구분코드', '일가정양립제도인지도_출산전후휴가제인지여부', '일가정양립제도인지도_배우자출산휴가제인지여부', '일가정양립제도인지도_육아휴직제인지여부', '일가정양립제도인지도_육아기근로시간단축제인지여부', '일가정양립제도인지도_직장보육지원인지여부', '일가정양립제도인지도_가족돌봄휴직제인지여부', '일가정양립제도인지도_유연근무제인지여부', '근로여건만족도_업무코드', '근로여건만족도_인사관리코드', '근로여건만족도_급여코드', '근로여건만족도_복리후생코드', '근로여건만족도_장래성코드', '근로여건만족도_근무환경코드', '근로여건만족도_인간관계코드', '근로여건만족도_근로시간코드', '근로여건만족도_직장내성희롱방지노력코드', '근로여건만족도_직장내교육훈련기회코드', '전반적일자리만족도코드', '거처종류코드', '점유형태코드', '배우자지난1주간경제활동여부', '가구소득코드', '분류코드_만13세이상여부', '분류코드_만15세이상여부', '분류코드_동부읍면부구분코드', '분류코드_성별코드', '분류코드_점유형태1코드', '분류코드_점유형태2코드', '분류코드_주택형태1코드', '분류코드_주택형태2코드', '분류코드_세대구분코드', '분류코드_가구원수', '분류코드_연령1코드', '분류코드_연령2코드', '분류코드_연령3코드', '분류코드_연령4코드', '분류코드_연령5코드', '분류코드_연령6코드', '분류코드_연령7코드', '분류코드_연령8코드', '분류코드_연령9코드', '분류코드_연령10코드', '분류코드_연령11코드', '분류코드_연령12코드', '분류코드_연령13코드', '분류코드_교육정도코드', '분류코드_혼인상태코드', '분류코드_경제활동여부', '분류코드_맞벌이1여부', '분류코드_맞벌이2여부', '분류코드_산업별코드', '분류코드_직업별코드', '분류코드_종사자지위코드', '분류코드_임금근로자구분코드', '분류코드_주관적만족감코드', '분류코드_가구소득1코드', '분류코드_가구소득2코드', '분류코드_연령성별1코드', '분류코드_연령성별2코드', '분류코드_연령성별3코드', '분류코드_연령성별4코드', '분류코드_연령성별5코드', '분류코드_연령성별6코드', '분류코드_연령성별7코드', '분류코드_연령성별8코드', '분류코드_연령성별9코드', '분류코드_연령교육정도별1코드', '분류코드_연령교육정도별2코드', '분류코드_연령교육정도별3코드', '분류코드_연령교육정도별4코드', '분류코드_연령교육정도별5코드', '분류코드_장애인복지카드_소유여부', '분류코드_기부여부', '분류코드_현금기부여부', '분류코드_현금기부정기성여부', '분류코드_물품기부여부', '분류코드_물품기부정기성여부', '분류코드_자원봉사여부', '분류코드_자원봉사정기성여부', '분류코드_계층의식코드', '분류코드_주관적소득수준코드', '분류코드_소득만족도코드', '분류코드_고용안전성코드', '분류코드_청소년교육정도1코드', '분류코드_청소년교육정도2코드', '가구가중값', '가구원가중값']
2017 features: ['가구일련번호', '가구원번호', '행정구역시도코드', '만연령', '성별코드', '주관적만족감코드', '가구주관계코드', '성취만족도코드', '교육정도코드', '재학상태코드', '혼인상태코드', '재학학년코드', '장애인복지카드_소유여부', '생활여건변화_전반적생활여건코드', '생활여건변화_보건의료서비스코드', '생활여건변화_사회보장제도코드', '생활여건변화_문화여가생활여건코드', '사회보험료부담인식_건강보험납부여부', '사회보험료부담인식_건강보험부담정도코드', '사회보험료부담인식_국민연금납부여부', '사회보험료부담인식_국민연금부담정도코드', '사회보험료부담인식_고용보험납부여부', '사회보험료부담인식_고용보험부담정도코드', '향후추가대상공공시설_1순위코드', '향후추가대상공공시설_2순위코드', '향후추가대상공공시설_3순위코드', '향후추가대상복지서비스_1순위코드', '향후추가대상복지서비스_2순위코드', '향후추가대상복지서비스_3순위코드', '선호장례방법코드', '사회장애인차별정도코드', '장애인유대관계여부', '장애인유대관계대상_1순위코드', '장애인관련시설견해코드', '장애인유대관계대상_2순위코드', '장애인복지사업견해코드', '장애인유대관계대상_3순위코드', '우선실시장애인복지사업_1순위코드', '장애구분인지여부', '우선실시장애인복지사업_2순위코드', '우선실시장애인복지사업_3순위코드', '노후준비방법_본인노후준비여부', '노후준비방법_주된방법코드', '노후준비방법_부수적방법코드', '노후준비방법_노후미준비사유코드', '노후사회적관심사코드', '노후희망활동코드', '생활비마련방법코드', '생활비마련방법_본인및배우자부담코드', '현재자녀동거여부', '현재자녀동거사유_1순위코드', '현재자녀동거사유_2순위코드', '현재자녀동거사유_3순위코드', '현재자녀비동거사유_1순위코드', '현재자녀비동거사유_2순위코드', '현재자녀비동거사유_3순위코드', '향후자녀동거의향여부', '향후희망거처코드', '사회적관계망_가사도움요청대상유무', '사회적관계망_가사도움요청대상인원수', '사회적관계망_자금차입도움요청대상유무', '개인적인간관계만족도코드', '사회적관계망_자금차입도움요청대상인원수', '사회적관계망_대화상대도움요청대상유무', '사회적관계망_대화상대도움요청대상인원수', '단체참여여부', '참여단체_1순위코드', '참여단체_2순위코드', '참여단체_3순위코드', '기부여부', '미기부사유코드', '기부내용_대상자직접후원_현금횟수', '기부내용_대상자직접후원_현금금액', '기부종류코드', '기부내용_언론기관후원_현금횟수', '기부내용_언론기관후원_현금금액', '정기기부_현금기부여부', '기부내용_모금단체후원_현금횟수', '정기기부_현금기부_주기코드', '기부내용_모금단체후원_현금금액', '정기기부_물품기부여부', '정기기부_물품기부_주기코드', '기부내용_종교단체후원_현금횟수', '기부내용_종교단체후원_현금금액', '기부내용_직장기업후원_현금횟수', '기부내용_직장기업후원_현금금액', '기부내용_기타_현금횟수', '기부내용_기타_현금금액', '기부희망분야_1순위코드', '기부내용_물품횟수', '기부희망분야_2순위코드', '기부희망분야_3순위코드', '향후기부의사여부', '기부문화확산_1순위코드', '기부문화확산_2순위코드', '기부문화확산_3순위코드', '자원봉사활동여부', '자원봉사활동_아동청소년노인장애인재소자관련횟수', '자원봉사활동_아동청소년노인장애인재소자관련시간수', '자원봉사활동_환경보전범죄예방관련횟수', '자원봉사활동_환경보전범죄예방관련시간수', '자원봉사활동_자녀교육관련횟수', '자원봉사활동_자녀교육관련시간수', '자원봉사활동_국가및지역행사관련횟수', '자원봉사활동_국가및지역행사관련시간수', '자원봉사활동_재해지역주민돕기및시설복구관련횟수', '자원봉사활동_재해지역주민돕기및시설복구관련시간수', '자원봉사활동_기타일반봉사관련횟수', '자원봉사활동_기타일반봉사관련시간수', '자원봉사활동정기성여부', '자원봉사활동정기성주기코드', '향후자원봉사활동의사여부', '계층의식코드', '본인세대_계층이동코드', '자식세대_계층이동코드', '신문_일반신문구독여부', '신문_일반신문구독주기코드', '신문_인터넷신문구독여부', '신문_인터넷신문구독주기코드', '독서여부', '독서_잡지류권수', '독서_교양서적권수', '독서_직업직무관련서적권수', '독서_생활취미정보서적권수', '독서_기타권수', '문화예술스포츠관람여부', '문화예술스포츠관람_음악연주회횟수', '문화예술스포츠관람_연극마당극뮤지컬횟수', '문화예술스포츠관람_무용횟수', '문화예술스포츠관람_영화횟수', '문화예술스포츠관람_박물관횟수', '문화예술스포츠관람_미술관횟수', '문화예술스포츠관람_스포츠횟수', '문화예술스포츠관람_기타횟수', '레저시설이용횟수', '레저시설_관광명소유적지국립공원이용횟수', '레저시설_온천장스파이용횟수', '레저시설_골프장이용횟수', '레저시설_스키장이용횟수', '레저시설_해수욕장이용횟수', '레저시설_산림욕장휴양림이용횟수', '레저시설_놀이공원이용횟수', '레저시설_수영장워터파크포함이용횟수', '레저시설_기타이용횟수', '국내관광여행경험여부', '국내관광여행_숙박여행횟수', '국내관광여행_숙박여행1회평균숙박일수', '국내관광여행_당일여행횟수', '해외여행경험여부', '해외여행경험_관광횟수', '해외여행경험_가족친지관련횟수', '해외여행경험_업무횟수', '해외여행경험_교육횟수', '주중여가활용_1순위코드', '주중여가활용_2순위코드', '주말휴일여가활용_1순위코드', '주중여가활용_3순위코드', '주말휴일여가활용_2순위코드', '주말휴일여가활용_3순위코드', '여가활용만족도코드', '주중여가활동_동반자코드', '여가활용불만족사유코드', '주말여가활동_동반자코드', '향후희망여가활동_1순위코드', '향후희망여가활동_2순위코드', '향후희망여가활동_3순위코드', '주관적소득수준코드', '소득변화코드', '부채변화코드', '내년가구재정상태코드', '긴축소비지출항목_1순위코드', '긴축소비지출항목_2순위코드', '긴축소비지출항목_3순위코드', '현재소득여부', '소득만족도코드', '소비생활만족도코드', '직업선택요인_1순위코드', '직업선택요인_2순위코드', '직업선택요인_3순위코드', '청년선호직장코드', '여성취업견해코드', '여성취업시기코드', '여성취업장애요인_1순위코드', '여성취업장애요인_2순위코드', '여성취업장애요인_3순위코드', '지난1주간경제활동여부', '일가정생활우선도코드', '고용안정성코드', '직장산업대분류코드', '직업대분류코드', '종사상지위코드', '임금근로자구분코드', '일가정양립제도인지도_출산전후휴가제인지여부', '일가정양립제도인지도_배우자출산휴가제인지여부', '일가정양립제도인지도_육아휴직제인지여부', '일가정양립제도인지도_육아기근로시간단축제인지여부', '일가정양립제도인지도_직장보육지원인지여부', '일가정양립제도인지도_가족돌봄휴직제인지여부', '일가정양립제도인지도_유연근무제인지여부', '근로여건만족도_업무코드', '근로여건만족도_인사관리코드', '근로여건만족도_급여코드', '근로여건만족도_복리후생코드', '근로여건만족도_장래성코드', '근로여건만족도_근무환경코드', '근로여건만족도_인간관계코드', '근로여건만족도_근로시간코드', '근로여건만족도_직장내교육훈련기회코드', '거처종류코드', '근로여건만족도_일가정양립직장문화코드', '점유형태코드', '근로여건만족도_직장내폭력방지노력코드', '배우자지난1주간경제활동여부', '가구소득코드', '근로여건만족도_전반적일자리코드', '분류코드_만13세이상여부', '분류코드_만15세이상여부', '분류코드_동부읍면부구분코드', '분류코드_성별코드', '분류코드_점유형태1코드', '분류코드_점유형태2코드', '분류코드_주택형태1코드', '분류코드_주택형태2코드', '분류코드_세대구분코드', '분류코드_가구원수', '분류코드_연령1코드', '분류코드_연령2코드', '분류코드_연령3코드', '분류코드_연령4코드', '분류코드_연령5코드', '분류코드_연령6코드', '분류코드_연령7코드', '분류코드_연령8코드', '분류코드_연령9코드', '분류코드_연령10코드', '분류코드_연령11코드', '분류코드_연령12코드', '분류코드_연령13코드', '분류코드_교육정도코드', '분류코드_혼인상태코드', '분류코드_경제활동여부', '분류코드_맞벌이1여부', '분류코드_맞벌이2여부', '분류코드_산업별코드', '분류코드_직업별코드', '분류코드_종사자지위코드', '분류코드_임금근로자구분코드', '분류코드_주관적만족감코드', '분류코드_가구소득1코드', '분류코드_가구소득2코드', '분류코드_연령성별1코드', '분류코드_연령성별2코드', '분류코드_연령성별3코드', '분류코드_연령성별4코드', '분류코드_가구소득3코드', '분류코드_연령성별5코드', '분류코드_연령성별6코드', '분류코드_연령성별7코드', '분류코드_연령성별8코드', '분류코드_연령성별9코드', '분류코드_연령교육정도별1코드', '분류코드_연령교육정도별2코드', '분류코드_연령교육정도별3코드', '분류코드_연령교육정도별4코드', '분류코드_연령교육정도별5코드', '분류코드_장애인복지카드_소유여부', '분류코드_기부여부', '분류코드_현금기부여부', '분류코드_현금기부정기성여부', '분류코드_물품기부여부', '분류코드_물품기부정기성여부', '분류코드_자원봉사여부', '분류코드_자원봉사정기성여부', '분류코드_계층의식코드', '분류코드_주관적소득수준코드', '분류코드_소득만족도코드', '분류코드_고용안전성코드', '분류코드_청소년교육정도1코드', '분류코드_청소년교육정도2코드', '가구가중값', '가구원가중값']
2019 features: ['가구일련번호', '가구원번호', '행정구역시도코드', '만연령', '성별코드', '주관적만족감코드', '가구주관계코드', '성취만족도코드', '교육정도코드', '재학상태코드', '혼인상태코드', '혼인신고여부', '장애인복지카드_소유여부', '생활여건변화_전반적생활여건코드', '생활여건변화_보건의료서비스코드', '생활여건변화_사회보장제도코드', '생활여건변화_문화여가생활여건코드', '사회보험료부담인식_건강보험납부여부', '사회보험료부담인식_건강보험부담정도코드', '사회보험료부담인식_국민연금납부여부', '사회보험료부담인식_국민연금부담정도코드', '사회보험료부담인식_고용보험납부여부', '사회보험료부담인식_고용보험부담정도코드', '향후추가대상공공시설_1순위코드', '향후추가대상공공시설_2순위코드', '향후추가대상공공시설_3순위코드', '향후추가대상복지서비스_1순위코드', '향후추가대상복지서비스_2순위코드', '향후추가대상복지서비스_3순위코드', '선호장례방법코드', '사회장애인차별정도코드', '장애인유대관계여부', '장애인유대관계대상_1순위코드', '장애인관련시설견해코드', '장애인유대관계대상_2순위코드', '장애인복지사업견해코드', '장애인유대관계대상_3순위코드', '우선실시장애인복지사업_1순위코드', '우선실시장애인복지사업_2순위코드', '우선실시장애인복지사업_3순위코드', '노후준비방법_본인노후준비여부', '노후준비방법_주된방법코드', '노후준비방법_부수적방법코드', '노후준비방법_노후미준비사유코드', '노후사회적관심사코드', '노후희망활동코드', '생활비마련방법코드', '생활비마련방법_본인및배우자부담코드', '현재자녀동거여부', '현재자녀동거사유_1순위코드', '자녀유무', '현재자녀동거사유_2순위코드', '현재자녀동거사유_3순위코드', '현재자녀비동거사유_1순위코드', '현재자녀비동거사유_2순위코드', '현재자녀비동거사유_3순위코드', '향후자녀동거의향여부', '향후희망거처코드', '사회적관계망_가사도움요청대상유무', '사회적관계망_가사도움요청대상인원수', '사회적관계망_자금차입도움요청대상유무', '개인적인간관계만족도코드', '사회적관계망_자금차입도움요청대상인원수', '신뢰코드', '사회적관계망_대화상대도움요청대상유무', '사회적관계망_대화상대도움요청대상인원수', '기부여부', '사회적관계망_교류가족친척유무', '미기부사유코드', '사회적관계망_교류가족친척인원수', '기부내용_대상자직접후원_현금횟수', '사회적관계망_교류가족친척외유무', '기부내용_대상자직접후원_현금금액', '사회적관계망_교류가족친척외인원수', '단체참여_친목사교단체여부', '기부종류코드', '기부내용_언론기관후원_현금횟수', '단체참여_종교단체여부', '기부내용_언론기관후원_현금금액', '단체참여_취미스포츠여가활동단체여부', '단체참여_시민사회단체여부', '기부내용_모금단체후원_현금횟수', '단체참여_학술단체여부', '기부내용_모금단체후원_현금금액', '단체참여_이익단체여부', '단체참여_정치단체여부', '기부내용_종교단체후원_현금횟수', '단체참여_지역사회모임여부', '기부내용_종교단체후원_현금금액', '단체참여_기타여부', '기부내용_직장기업후원_현금횟수', '기부내용_직장기업후원_현금금액', '기부내용_기타_현금횟수', '기부내용_기타_현금금액', '기부내용_대상자직접후원_현금주기코드', '기부내용_언론기관후원_현금주기코드', '기부희망분야_1순위코드', '기부내용_물품횟수', '기부희망분야_2순위코드', '기부희망분야_3순위코드', '기부내용_모금단체후원_현금주기코드', '향후기부의사여부', '기부문화확산_1순위코드', '유산기부의사여부', '기부내용_종교단체후원_현금주기코드', '기부문화확산_2순위코드', '기부문화확산_3순위코드', '기부내용_직장기업후원_현금주기코드', '자원봉사활동여부', '자원봉사활동_아동청소년노인장애인재소자관련횟수', '자원봉사활동_아동청소년노인장애인재소자관련시간수', '기부내용_기타_현금주기코드', '자원봉사활동_환경보전범죄예방관련횟수', '자원봉사활동_환경보전범죄예방관련시간수', '기부내용_물품주기코드', '자원봉사활동_자녀교육관련횟수', '자원봉사활동_자녀교육관련시간수', '자원봉사활동_국가및지역행사관련횟수', '자원봉사활동_국가및지역행사관련시간수', '자원봉사활동_재해지역주민돕기및시설복구관련횟수', '자원봉사활동_재해지역주민돕기및시설복구관련시간수', '자원봉사활동_기타일반봉사관련횟수', '자원봉사활동_기타일반봉사관련시간수', '향후자원봉사활동의사여부', '전문성활용자원봉사활동_참석여부', '계층의식코드', '본인세대_계층이동코드', '자원봉사활동_아동청소년노인장애인재소자관련주기코드', '자식세대_계층이동코드', '신문_일반신문구독여부', '자원봉사활동_환경보전범죄예방관련주기코드', '신문_인터넷신문구독여부', '자원봉사활동_자녀교육관련주기코드', '독서여부', '독서_잡지류권수', '독서_교양서적권수', '독서_직업직무관련서적권수', '자원봉사활동_국가및지역행사관련주기코드', '독서_생활취미정보서적권수', '독서_기타권수', '문화예술스포츠관람여부', '자원봉사활동_재해지역주민돕기및시설복구관련주기코드', '문화예술스포츠관람_연극마당극뮤지컬횟수', '자원봉사활동_기타일반봉사관련주기코드', '문화예술스포츠관람_무용횟수', '문화예술스포츠관람_영화횟수', '전문성활용자원봉사활동_구분코드', '문화예술스포츠관람_박물관횟수', '문화예술스포츠관람_미술관횟수', '문화예술스포츠관람_스포츠횟수', '문화예술스포츠관람_기타횟수', '레저시설이용횟수', '신문_일반신문구독분야코드', '레저시설_관광명소유적지국립공원이용횟수', '레저시설_온천장스파이용횟수', '신문_인터넷신문구독분야코드', '레저시설_골프장이용횟수', '레저시설_해수욕장이용횟수', '레저시설_산림욕장휴양림이용횟수', '레저시설_놀이공원이용횟수', '레저시설_수영장워터파크포함이용횟수', '레저시설_기타이용횟수', '국내관광여행경험여부', '국내관광여행_숙박여행횟수', '문화예술스포츠관람_음악연주회콘서트횟수', '국내관광여행_숙박여행1회평균숙박일수', '국내관광여행_당일여행횟수', '해외여행경험여부', '해외여행경험_관광횟수', '해외여행경험_가족친지관련횟수', '해외여행경험_업무횟수', '해외여행경험_교육횟수', '주중여가활용_1순위코드', '주중여가활용_2순위코드', '주말휴일여가활용_1순위코드', '주중여가활용_3순위코드', '주말휴일여가활용_2순위코드', '주말휴일여가활용_3순위코드', '레저시설_스키장스케이트장이용횟수', '여가활용만족도코드', '주중여가활동_동반자코드', '여가활용불만족사유코드', '주말여가활동_동반자코드', '향후희망여가활동_1순위코드', '향후희망여가활동_2순위코드', '향후희망여가활동_3순위코드', '주관적소득수준코드', '소득변화코드', '부채변화코드', '내년가구재정상태코드', '긴축소비지출항목_1순위코드', '긴축소비지출항목_2순위코드', '긴축소비지출항목_3순위코드', '현재소득여부', '소득만족도코드', '소비생활만족도코드', '직업선택요인_1순위코드', '직업선택요인_2순위코드', '직업선택요인_3순위코드', '청년선호직장코드', '여성취업견해코드', '여성취업시기코드', '여성취업장애요인_1순위코드', '여성취업장애요인_2순위코드', '여성취업장애요인_3순위코드', '지난1주간경제활동여부', '일가정생활우선도코드', '고용안정성코드', '직장산업대분류코드', '직업대분류코드', '종사상지위코드', '임금근로자구분코드', '근로여건만족도_업무코드', '근로여건만족도_인사관리코드', '근로여건만족도_급여코드', '근로여건만족도_복리후생코드', '근로여건만족도_장래성코드', '근로여건만족도_근무환경코드', '근로여건만족도_인간관계코드', '근로여건만족도_근로시간코드', '근로여건만족도_직장내교육훈련기회코드', '거처종류코드', '근로여건만족도_일가정양립직장문화코드', '점유형태코드', '근로여건만족도_직장내폭력방지노력코드', '배우자지난1주간경제활동여부', '가구소득코드', '근로여건만족도_전반적일자리코드', '분류코드_만13세이상여부', '분류코드_만15세이상여부', '분류코드_동부읍면부구분코드', '분류코드_성별코드', '분류코드_점유형태1코드', '분류코드_점유형태2코드', '분류코드_주택형태1코드', '분류코드_주택형태2코드', '분류코드_세대구분코드', '분류코드_가구원수', '분류코드_연령1코드', '분류코드_연령2코드', '분류코드_연령3코드', '분류코드_연령4코드', '분류코드_연령5코드', '분류코드_연령6코드', '분류코드_연령7코드', '분류코드_연령8코드', '분류코드_연령9코드', '분류코드_연령10코드', '분류코드_연령11코드', '분류코드_연령12코드', '분류코드_연령13코드', '분류코드_교육정도코드', '분류코드_혼인상태코드', '분류코드_경제활동여부', '분류코드_맞벌이1여부', '분류코드_맞벌이2여부', '분류코드_산업별코드', '분류코드_직업별코드', '분류코드_종사자지위코드', '분류코드_임금근로자구분코드', '분류코드_주관적만족감코드', '분류코드_가구소득1코드', '분류코드_가구소득2코드', '분류코드_연령성별1코드', '분류코드_연령성별2코드', '분류코드_연령성별3코드', '분류코드_연령성별4코드', '분류코드_연령성별5코드', '분류코드_연령성별6코드', '분류코드_연령성별7코드', '분류코드_연령성별8코드', '분류코드_연령성별9코드', '분류코드_연령교육정도별1코드', '분류코드_연령교육정도별2코드', '분류코드_연령교육정도별3코드', '분류코드_연령교육정도별4코드', '분류코드_연령교육정도별5코드', '분류코드_장애인복지카드_소유여부', '분류코드_기부여부', '분류코드_현금기부여부', '분류코드_현금기부정기성여부', '분류코드_물품기부여부', '분류코드_물품기부정기성여부', '분류코드_자원봉사여부', '분류코드_자원봉사정기성여부', '분류코드_계층의식코드', '분류코드_주관적소득수준코드', '분류코드_소득만족도코드', '분류코드_청소년교육정도1코드', '분류코드_청소년교육정도2코드', '가구가중값', '가구원가중값', '분류코드_고용안정성여부']

In [4]:
cols_2015 = set(features["2015"])
cols_2017 = set(features["2017"])
cols_2019 = set(features["2019"])
cols_2021 = set(features["2021"])
cols_2023 = set(features["2023"])

In [5]:
all_items = sorted(cols_2015 | cols_2017 | cols_2019 | cols_2021 | cols_2023)
compare_df = pd.DataFrame({
    "항목명": all_items,
    "2015": [item in cols_2015 for item in all_items],
    "2017": [item in cols_2017 for item in all_items],
    "2019": [item in cols_2019 for item in all_items],
    "2021": [item in cols_2021 for item in all_items],
    "2023": [item in cols_2023 for item in all_items],
})

# 각 행에서 True 개수 세기
compare_df["True_count"] = (compare_df[["2015", "2017", "2019", "2021", "2023"]]).sum(axis=1)

# 출력 옵션: 열 다 보이도록
# 출력 옵션 늘리기
pd.set_option("display.max_rows", None)      # 행 전부 출력
pd.set_option("display.max_columns", None)  # 열 전부 출력
pd.set_option("display.width", None)        # 줄바꿈 없이 한 줄로 출력
pd.set_option("display.max_colwidth", None) # 셀 안 텍스트 길이 제한 해제

print(compare_df)

                                        항목명   2015   2017   2019   2021  \
0                                     가구가중값   True   True   True   True
1                                    가구소득코드   True   True   True   True
2                                    가구원가중값   True   True   True   True
3                                     가구원번호   True   True   True   True
4                                    가구일련번호   True   True   True   True
5                                   가구주관계코드   True   True   True   True
6                              개인적인간관계만족도코드  False   True   True   True
7                                    거처종류코드   True   True   True   True
8                                    계층의식코드   True   True   True   True
9                        고용안정성_불안사유_코로나관련여부  False  False  False   True
10                                  고용안정성코드   True   True   True   True
11                               과거해외여행경험여부   True  False  False  False
12                                   교육정도코드   True   True   True   True
13                            국내관광여행_당일여행횟수   True   True   True   True
14                     국내관광여행_미경험사유_코로나관련여부  False  False  False   True
15                      국내관광여행_숙박여행1회평균숙박일수   True   True   True   True
16                            국내관광여행_숙박여행횟수   True   True   True   True
17                               국내관광여행경험여부   True   True   True   True
18                           근로여건만족도_근로시간코드   True   True   True   True
19                           근로여건만족도_근무환경코드   True   True   True   True
20                             근로여건만족도_급여코드   True   True   True   True
21                           근로여건만족도_복리후생코드   True   True   True   True
22                             근로여건만족도_업무코드   True   True   True   True
23                           근로여건만족도_인간관계코드   True   True   True   True
24                           근로여건만족도_인사관리코드   True   True   True   True
25                      근로여건만족도_일가정양립직장문화코드  False   True   True   True
26                            근로여건만족도_장래성코드   True   True   True   True
27                         근로여건만족도_전반적일자리코드  False   True   True   True
28                      근로여건만족도_직장내교육훈련기회코드   True   True   True   True
29                     근로여건만족도_직장내성희롱방지노력코드   True  False  False  False
30                      근로여건만족도_직장내폭력방지노력코드  False   True   True   True
31                             기부내용_기타_물품횟수   True  False  False  False
32                             기부내용_기타_현금금액   True   True   True   True
33                           기부내용_기타_현금주기코드  False  False   True  False
34                             기부내용_기타_현금횟수   True   True   True   True
35                        기부내용_대상자직접후원_물품횟수   True  False  False  False
36                        기부내용_대상자직접후원_현금금액   True   True   True   True
37                      기부내용_대상자직접후원_현금주기코드  False  False   True  False
38                        기부내용_대상자직접후원_현금횟수   True   True   True   True
39                         기부내용_모금단체후원_현금금액   True   True   True   True
40                       기부내용_모금단체후원_현금주기코드  False  False   True  False
41                         기부내용_모금단체후원_현금횟수   True   True   True   True
42                              기부내용_물품주기코드  False  False   True  False
43                                기부내용_물품횟수  False   True   True   True
44                       기부내용_물품후원단체후원_물품횟수   True  False  False  False
45                         기부내용_언론기관후원_물품횟수   True  False  False  False
46                         기부내용_언론기관후원_현금금액   True   True   True   True
47                       기부내용_언론기관후원_현금주기코드  False  False   True  False
48                         기부내용_언론기관후원_현금횟수   True   True   True   True
49                         기부내용_종교단체후원_물품횟수   True  False  False  False
50                         기부내용_종교단체후원_현금금액   True   True   True   True
51                       기부내용_종교단체후원_현금주기코드  False  False   True  False
52                         기부내용_종교단체후원_현금횟수   True   True   True   True
53                         기부내용_직장기업후원_물품횟수   True  False  False  False
54                         기부내용_직장기업후원_현금금액   True   True   True   True
55                       기부내용_직장기업후원_현금주기코드  False  False   True  False
56                         기부내용_직장기업후원_현금횟수   True   True   True   True
57                               기부대상인지경로코드   True  False  False  False
58                             기부문화확산_1순위코드   True   True   True   True
59                             기부문화확산_2순위코드   True   True   True   True
60                             기부문화확산_3순위코드   True   True   True   True
61                                   기부사유코드  False  False  False   True
62                                     기부여부   True   True   True   True
63                                   기부종류코드  False   True   True  False
64                             기부희망분야_1순위코드   True   True   True   True
65                             기부희망분야_2순위코드   True   True   True   True
66                             기부희망분야_3순위코드   True   True   True   True
67                           긴축소비지출항목_1순위코드   True   True   True   True
68                           긴축소비지출항목_2순위코드   True   True   True   True
69                           긴축소비지출항목_3순위코드   True   True   True   True
70                               내년가구재정상태코드   True   True   True   True
71                               노후사회적관심사코드   True   True   True  False
72                              노후사회적역할기타내용  False  False  False   True
73                                노후사회적역할코드  False  False  False  False
74                           노후생활주요활동_1순위코드  False  False  False  False
75                           노후생활주요활동_2순위코드  False  False  False  False
76                           노후생활주요활동_3순위코드  False  False  False  False
77                         노후준비방법_노후미준비사유코드   True   True   True   True
78                          노후준비방법_본인노후준비여부   True   True   True   True
79                           노후준비방법_부수적방법코드   True   True   True   True
80                            노후준비방법_주된방법코드   True   True   True   True
81                             노후희망활동_1순위코드  False  False  False  False
82                             노후희망활동_2순위코드  False  False  False  False
83                             노후희망활동_3순위코드  False  False  False  False
84                                 노후희망활동코드   True   True   True   True
85                                  다문화가족여부  False  False  False  False
86                          단체참여_기타_코로나관련여부  False  False  False   True
87                                단체참여_기타여부  False  False   True   True
88                      단체참여_시민사회단체_코로나관련여부  False  False  False   True
89                            단체참여_시민사회단체여부  False  False   True   True
90                        단체참여_이익단체_코로나관련여부  False  False  False   True
91                              단체참여_이익단체여부  False  False   True   True
92                        단체참여_정치단체_코로나관련여부  False  False  False   True
93                              단체참여_정치단체여부  False  False   True   True
94                        단체참여_종교단체_코로나관련여부  False  False  False   True
95                              단체참여_종교단체여부  False  False   True   True
96                      단체참여_지역사회모임_코로나관련여부  False  False  False   True
97                            단체참여_지역사회모임여부  False  False   True   True
98                 단체참여_취미스포츠여가활동단체_코로나관련여부  False  False  False   True
99                       단체참여_취미스포츠여가활동단체여부  False  False   True   True
100                     단체참여_친목사교단체_코로나관련여부  False  False  False   True
101                           단체참여_친목사교단체여부  False  False   True   True
102                       단체참여_학술단체_코로나관련여부  False  False  False   True
103                             단체참여_학술단체여부  False  False   True   True
104                                  단체참여여부   True   True  False  False
105                           독서_교양서적_전자책권수  False  False  False   True
106                           독서_교양서적_종이책권수  False  False  False   True
107                               독서_교양서적권수   True   True   True   True
108                            독서_기타_오디오북권수  False  False  False   True
109                             독서_기타_전자책권수  False  False  False   True
110                             독서_기타_종이책권수  False  False  False   True
111                                 독서_기타권수   True   True   True   True
112                      독서_생활취미정보서적_오디오북권수  False  False  False   True
113                       독서_생활취미정보서적_전자책권수  False  False  False   True
114                       독서_생활취미정보서적_종이책권수  False  False  False   True
115                           독서_생활취미정보서적권수   True   True   True   True
116                          독서_오디오북_교양서적권수  False  False  False   True
117                           독서_잡지류_오디오북권수  False  False  False   True
118                            독서_잡지류_전자책권수  False  False  False   True
119                            독서_잡지류_종이책권수  False  False  False   True
120                                독서_잡지류권수   True   True   True   True
121                      독서_직업직무관련서적_오디오북권수  False  False  False   True
122                       독서_직업직무관련서적_전자책권수  False  False  False   True
123                       독서_직업직무관련서적_종이책권수  False  False  False   True
124                           독서_직업직무관련서적권수   True   True   True   True
125                                    독서여부   True   True   True   True
126                            레저시설_골프장이용횟수   True   True   True   True
127                    레저시설_관광명소유적지국립공원이용횟수   True   True   True   True
128                             레저시설_기타이용횟수   True   True   True   True
129                           레저시설_놀이공원이용횟수   True   True   True   True
130                        레저시설_산림욕장휴양림이용횟수   True   True   True   True
131                      레저시설_수영장워터파크포함이용횟수   True   True   True   True
132                       레저시설_스키장스케이트장이용횟수  False  False   True   True
133                            레저시설_스키장이용횟수   True   True  False  False
134                          레저시설_온천장스파이용횟수   True   True   True   True
135                             레저시설_이용여부코드  False  False  False  False
136                           레저시설_해수욕장이용횟수   True   True   True   True
137                                레저시설이용횟수   True   True   True   True
138                                     만연령   True   True   True   True
139                          문화예술스포츠관람_기타횟수  False   True   True   True
140                      문화예술스포츠관람_무용_온라인횟수  False  False  False   True
141                          문화예술스포츠관람_무용횟수   True   True   True   True
142           문화예술스포츠관람_문학행사(시화전도서전시회)_관람횟수  False  False  False  False
143                     문화예술스포츠관람_미술관_온라인횟수  False  False  False   True
144                         문화예술스포츠관람_미술관횟수   True   True   True   True
145                     문화예술스포츠관람_박물관_온라인횟수  False  False  False   True
146                         문화예술스포츠관람_박물관횟수   True   True   True   True
147                         문화예술스포츠관람_스포츠횟수   True   True   True   True
148                문화예술스포츠관람_연극마당극뮤지컬_온라인횟수  False  False  False   True
149                    문화예술스포츠관람_연극마당극뮤지컬횟수   True   True   True   True
150                          문화예술스포츠관람_영화횟수   True   True   True   True
151                문화예술스포츠관람_음악연주회콘서트_온라인횟수  False  False  False   True
152                    문화예술스포츠관람_음악연주회콘서트횟수  False  False   True   True
153                       문화예술스포츠관람_음악연주회횟수   True   True  False  False
154                             문화예술스포츠관람여부   True   True   True   True
155                                 미기부사유코드   True   True   True   True
156                          배우자지난1주간경제활동여부   True   True   True   True
157                              본인방역수칙준수코드  False  False  False   True
158                             본인세대_계층이동코드   True   True   True   True
159                       부채변화_증가사유_코로나관련여부  False  False  False   True
160                                  부채변화코드   True   True   True   True
161                            분류코드_가구소득1코드   True   True   True   True
162                            분류코드_가구소득2코드   True   True   True   True
163                            분류코드_가구소득3코드  False   True  False   True
164                               분류코드_가구원수   True   True   True   True
165                            분류코드_가구원수2코드  False  False  False   True
166                            분류코드_경제활동2여부  False  False  False   True
167                             분류코드_경제활동여부   True   True   True   True
168                             분류코드_계층의식코드   True   True   True   True
169                            분류코드_고용안전성코드   True   True  False  False
170                            분류코드_고용안정성여부  False  False   True   True
171                             분류코드_교육정도코드   True   True   True   True
172                               분류코드_기부여부   True   True   True   True
173                            분류코드_다문화가족여부  False  False  False  False
174                          분류코드_동부읍면부구분코드   True   True   True   True
175                           분류코드_만13세이상여부   True   True   True   True
176                           분류코드_만15세이상여부   True   True   True   True
177                             분류코드_맞벌이1여부   True   True   True   True
178                             분류코드_맞벌이2여부   True   True   True   True
179                             분류코드_물품기부여부   True   True   True   True
180                          분류코드_물품기부정기성여부   True   True   True  False
181                              분류코드_산업별코드   True   True   True   True
182                               분류코드_성별코드   True   True   True   True
183                             분류코드_세대구분코드   True   True   True   True
184                            분류코드_소득만족도코드   True   True   True   True
185                             분류코드_연령10코드   True   True   True   True
186                             분류코드_연령11코드   True   True   True   True
187                             분류코드_연령12코드   True   True   True   True
188                             분류코드_연령13코드   True   True   True   True
189                             분류코드_연령14코드  False  False  False   True
190                             분류코드_연령15코드  False  False  False  False
191                             분류코드_연령16코드  False  False  False  False
192                              분류코드_연령1코드   True   True   True   True
193                              분류코드_연령2코드   True   True   True   True
194                              분류코드_연령3코드   True   True   True   True
195                              분류코드_연령4코드   True   True   True   True
196                              분류코드_연령5코드   True   True   True   True
197                              분류코드_연령6코드   True   True   True   True
198                              분류코드_연령7코드   True   True   True   True
199                              분류코드_연령8코드   True   True   True   True
200                              분류코드_연령9코드   True   True   True   True
201                         분류코드_연령교육정도별1코드   True   True   True   True
202                         분류코드_연령교육정도별2코드   True   True   True   True
203                         분류코드_연령교육정도별3코드   True   True   True   True
204                         분류코드_연령교육정도별4코드   True   True   True   True
205                         분류코드_연령교육정도별5코드   True   True   True   True
206                         분류코드_연령교육정도별6코드  False  False  False   True
207                         분류코드_연령교육정도별7코드  False  False  False  False
208                           분류코드_연령성별10코드  False  False  False   True
209                           분류코드_연령성별11코드  False  False  False   True
210                            분류코드_연령성별1코드   True   True   True   True
211                            분류코드_연령성별2코드   True   True   True   True
212                            분류코드_연령성별3코드   True   True   True   True
213                            분류코드_연령성별4코드   True   True   True   True
214                            분류코드_연령성별5코드   True   True   True   True
215                            분류코드_연령성별6코드   True   True   True   True
216                            분류코드_연령성별7코드   True   True   True   True
217                            분류코드_연령성별8코드   True   True   True   True
218                            분류코드_연령성별9코드   True   True   True   True
219                          분류코드_임금근로자구분코드   True   True   True   True
220                             분류코드_자원봉사여부   True   True   True   True
221                          분류코드_자원봉사정기성여부   True   True   True  False
222                       분류코드_장애인복지카드_소유여부   True   True   True   True
223                            분류코드_점유형태1코드   True   True   True   True
224                            분류코드_점유형태2코드   True   True   True   True
225                            분류코드_종사자지위코드   True   True   True   True
226                           분류코드_주관적만족감코드   True   True   True   True
227                          분류코드_주관적소득수준코드   True   True   True   True
228                            분류코드_주택형태1코드   True   True   True   True
229                            분류코드_주택형태2코드   True   True   True   True
230                              분류코드_직업별코드   True   True   True   True
231                         분류코드_청소년교육정도1코드   True   True   True   True
232                         분류코드_청소년교육정도2코드   True   True   True   True
233                             분류코드_현금기부여부   True   True   True   True
234                          분류코드_현금기부정기성여부   True   True   True  False
235                            분류코드_혼인상태2코드  False  False  False   True
236                             분류코드_혼인상태코드   True   True   True   True
237                      사회보험료부담인식_건강보험납부여부   True   True   True  False
238                    사회보험료부담인식_건강보험부담정도코드   True   True   True  False
239                      사회보험료부담인식_고용보험납부여부   True   True   True  False
240                    사회보험료부담인식_고용보험부담정도코드   True   True   True  False
241                      사회보험료부담인식_국민연금납부여부   True   True   True  False
242                    사회보험료부담인식_국민연금부담정도코드   True   True   True  False
243                             사회장애인차별정도코드   True   True   True   True
244                       사회적관계망_가사도움요청대상유무   True   True   True   True
245                      사회적관계망_가사도움요청대상인원수   True   True   True   True
246                        사회적관계망_교류가족친척외유무  False  False   True   True
247                       사회적관계망_교류가족친척외인원수  False  False   True   True
248                         사회적관계망_교류가족친척유무  False  False   True   True
249                        사회적관계망_교류가족친척인원수  False  False   True   True
250                     사회적관계망_대화상대도움요청대상유무   True   True   True   True
251                    사회적관계망_대화상대도움요청대상인원수   True   True   True   True
252                     사회적관계망_자금차입도움요청대상유무   True   True   True   True
253                    사회적관계망_자금차입도움요청대상인원수   True   True   True   True
254                      사회적관계망변화_가족_변화정도코드  False  False  False   True
255                  사회적관계망변화_가족외친인척_변화정도코드  False  False  False   True
256                    사회적관계망변화_기타지인_변화정도코드  False  False  False   True
257                      사회적관계망변화_동료_변화정도코드  False  False  False   True
258                      사회적관계망변화_이웃_변화정도코드  False  False  False   True
259                 사회적관계망변화_종교단체구성원_변화정도코드  False  False  False   True
260                사회적관계망변화_취미활동단체회원_변화정도코드  False  False  False   True
261                      사회적관계망변화_친구_변화정도코드  False  False  False   True
262                      생활비마련방법_본인및배우자부담코드   True   True   True   True
263                     생활비마련방법_지원자녀및친척동거여부   True  False  False  False
264                               생활비마련방법코드   True   True   True   True
265                 생활여건변화_문화여가생활여건_코로나관련여부  False  False  False   True
266                       생활여건변화_문화여가생활여건코드   True   True   True   True
267                  생활여건변화_보건의료서비스_코로나관련여부  False  False  False   True
268                        생활여건변화_보건의료서비스코드   True   True   True   True
269                   생활여건변화_사회보장제도_코로나관련여부  False  False  False   True
270                         생활여건변화_사회보장제도코드   True   True   True   True
271                  생활여건변화_전반적생활여건_코로나관련여부  False  False  False   True
272                        생활여건변화_전반적생활여건코드   True   True   True   True
273                                선호장례방법코드   True   True   True   True
274                                    성별코드   True   True   True   True
275                                 성취만족도코드  False   True   True   True

In [6]:
compare_df.to_csv("항목명_일치여부비교.csv", index=False, encoding="utf-8-sig")

In [7]:
import re

def normalize_column(col):
    # 한글+숫자+영문만 남기고, 나머지는 제거
    col = re.sub(r"[^가-힣A-Za-z0-9()_]", "", col)
    # 소문자로 변환
    col = col.lower()
    # 맨 뒷 글자 '코드' 제거
    col = re.sub(r"코드$", "", col)
    return col

delete_blink = [normalize_column(c) for c in compare_df["항목명"]]

In [8]:
compare_df["항목명"]

0                                       가구가중값
1                                      가구소득코드
2                                      가구원가중값
3                                       가구원번호
4                                      가구일련번호
5                                     가구주관계코드
6                                개인적인간관계만족도코드
7                                      거처종류코드
8                                      계층의식코드
9                          고용안정성_불안사유_코로나관련여부
10                                    고용안정성코드
11                                 과거해외여행경험여부
12                                     교육정도코드
13                              국내관광여행_당일여행횟수
14                       국내관광여행_미경험사유_코로나관련여부
15                        국내관광여행_숙박여행1회평균숙박일수
16                              국내관광여행_숙박여행횟수
17                                 국내관광여행경험여부
18                             근로여건만족도_근로시간코드
19                             근로여건만족도_근무환경코드
20                               근로여건만족도_급여코드
21                             근로여건만족도_복리후생코드
22                               근로여건만족도_업무코드
23                             근로여건만족도_인간관계코드
24                             근로여건만족도_인사관리코드
25                        근로여건만족도_일가정양립직장문화코드
26                              근로여건만족도_장래성코드
27                           근로여건만족도_전반적일자리코드
28                        근로여건만족도_직장내교육훈련기회코드
29                       근로여건만족도_직장내성희롱방지노력코드
30                        근로여건만족도_직장내폭력방지노력코드
31                               기부내용_기타_물품횟수
32                               기부내용_기타_현금금액
33                             기부내용_기타_현금주기코드
34                               기부내용_기타_현금횟수
35                          기부내용_대상자직접후원_물품횟수
36                          기부내용_대상자직접후원_현금금액
37                        기부내용_대상자직접후원_현금주기코드
38                          기부내용_대상자직접후원_현금횟수
39                           기부내용_모금단체후원_현금금액
40                         기부내용_모금단체후원_현금주기코드
41                           기부내용_모금단체후원_현금횟수
42                                기부내용_물품주기코드
43                                  기부내용_물품횟수
44                         기부내용_물품후원단체후원_물품횟수
45                           기부내용_언론기관후원_물품횟수
46                           기부내용_언론기관후원_현금금액
47                         기부내용_언론기관후원_현금주기코드
48                           기부내용_언론기관후원_현금횟수
49                           기부내용_종교단체후원_물품횟수
50                           기부내용_종교단체후원_현금금액
51                         기부내용_종교단체후원_현금주기코드
52                           기부내용_종교단체후원_현금횟수
53                           기부내용_직장기업후원_물품횟수
54                           기부내용_직장기업후원_현금금액
55                         기부내용_직장기업후원_현금주기코드
56                           기부내용_직장기업후원_현금횟수
57                                 기부대상인지경로코드
58                               기부문화확산_1순위코드
59                               기부문화확산_2순위코드
60                               기부문화확산_3순위코드
61                                     기부사유코드
62                                       기부여부
63                                     기부종류코드
64                               기부희망분야_1순위코드
65                               기부희망분야_2순위코드
66                               기부희망분야_3순위코드
67                             긴축소비지출항목_1순위코드
68                             긴축소비지출항목_2순위코드
69                             긴축소비지출항목_3순위코드
70                                 내년가구재정상태코드
71                                 노후사회적관심사코드
72                                노후사회적역할기타내용
73                                  노후사회적역할코드
74                             노후생활주요활동_1순위코드
75                             노후생활주요활동_2순위코드
76                             노후생활주요활동_3순위코드
77                           노후준비방법_노후미준비사유코드
78                            노후준비방법_본인노후준비여부
79                             노후준비방법_부수적방법코드
80                              노후준비방법_주된방법코드
81                               노후희망활동_1순위코드
82                               노후희망활동_2순위코드
83                               노후희망활동_3순위코드
84                                   노후희망활동코드
85                                    다문화가족여부
86                            단체참여_기타_코로나관련여부
87                                  단체참여_기타여부
88                        단체참여_시민사회단체_코로나관련여부
89                              단체참여_시민사회단체여부
90                          단체참여_이익단체_코로나관련여부
91                                단체참여_이익단체여부
92                          단체참여_정치단체_코로나관련여부
93                                단체참여_정치단체여부
94                          단체참여_종교단체_코로나관련여부
95                                단체참여_종교단체여부
96                        단체참여_지역사회모임_코로나관련여부
97                              단체참여_지역사회모임여부
98                   단체참여_취미스포츠여가활동단체_코로나관련여부
99                         단체참여_취미스포츠여가활동단체여부
100                       단체참여_친목사교단체_코로나관련여부
101                             단체참여_친목사교단체여부
102                         단체참여_학술단체_코로나관련여부
103                               단체참여_학술단체여부
104                                    단체참여여부
105                             독서_교양서적_전자책권수
106                             독서_교양서적_종이책권수
107                                 독서_교양서적권수
108                              독서_기타_오디오북권수
109                               독서_기타_전자책권수
110                               독서_기타_종이책권수
111                                   독서_기타권수
112                        독서_생활취미정보서적_오디오북권수
113                         독서_생활취미정보서적_전자책권수
114                         독서_생활취미정보서적_종이책권수
115                             독서_생활취미정보서적권수
116                            독서_오디오북_교양서적권수
117                             독서_잡지류_오디오북권수
118                              독서_잡지류_전자책권수
119                              독서_잡지류_종이책권수
120                                  독서_잡지류권수
121                        독서_직업직무관련서적_오디오북권수
122                         독서_직업직무관련서적_전자책권수
123                         독서_직업직무관련서적_종이책권수
124                             독서_직업직무관련서적권수
125                                      독서여부
126                              레저시설_골프장이용횟수
127                      레저시설_관광명소유적지국립공원이용횟수
128                               레저시설_기타이용횟수
129                             레저시설_놀이공원이용횟수
130                          레저시설_산림욕장휴양림이용횟수
131                        레저시설_수영장워터파크포함이용횟수
132                         레저시설_스키장스케이트장이용횟수
133                              레저시설_스키장이용횟수
134                            레저시설_온천장스파이용횟수
135                               레저시설_이용여부코드
136                             레저시설_해수욕장이용횟수
137                                  레저시설이용횟수
138                                       만연령
139                            문화예술스포츠관람_기타횟수
140                        문화예술스포츠관람_무용_온라인횟수
141                            문화예술스포츠관람_무용횟수
142             문화예술스포츠관람_문학행사(시화전도서전시회)_관람횟수
143                       문화예술스포츠관람_미술관_온라인횟수
144                           문화예술스포츠관람_미술관횟수
145                       문화예술스포츠관람_박물관_온라인횟수
146                           문화예술스포츠관람_박물관횟수
147                           문화예술스포츠관람_스포츠횟수
148                  문화예술스포츠관람_연극마당극뮤지컬_온라인횟수
149                      문화예술스포츠관람_연극마당극뮤지컬횟수
150                            문화예술스포츠관람_영화횟수
151                  문화예술스포츠관람_음악연주회콘서트_온라인횟수
152                      문화예술스포츠관람_음악연주회콘서트횟수
153                         문화예술스포츠관람_음악연주회횟수
154                               문화예술스포츠관람여부
155                                   미기부사유코드
156                            배우자지난1주간경제활동여부
157                                본인방역수칙준수코드
158                               본인세대_계층이동코드
159                         부채변화_증가사유_코로나관련여부
160                                    부채변화코드
161                              분류코드_가구소득1코드
162                              분류코드_가구소득2코드
163                              분류코드_가구소득3코드
164                                 분류코드_가구원수
165                              분류코드_가구원수2코드
166                              분류코드_경제활동2여부
167                               분류코드_경제활동여부
168                               분류코드_계층의식코드
169                              분류코드_고용안전성코드
170                              분류코드_고용안정성여부
171                               분류코드_교육정도코드
172                                 분류코드_기부여부
173                              분류코드_다문화가족여부
174                            분류코드_동부읍면부구분코드
175                             분류코드_만13세이상여부
176                             분류코드_만15세이상여부
177                               분류코드_맞벌이1여부
178                               분류코드_맞벌이2여부
179                               분류코드_물품기부여부
180                            분류코드_물품기부정기성여부
181                                분류코드_산업별코드
182                                 분류코드_성별코드
183                               분류코드_세대구분코드
184                              분류코드_소득만족도코드
185                               분류코드_연령10코드
186                               분류코드_연령11코드
187                               분류코드_연령12코드
188                               분류코드_연령13코드
189                               분류코드_연령14코드
190                               분류코드_연령15코드
191                               분류코드_연령16코드
192                                분류코드_연령1코드
193                                분류코드_연령2코드
194                                분류코드_연령3코드
195                                분류코드_연령4코드
196                                분류코드_연령5코드
197                                분류코드_연령6코드
198                                분류코드_연령7코드
199                                분류코드_연령8코드
200                                분류코드_연령9코드
201                           분류코드_연령교육정도별1코드
202                           분류코드_연령교육정도별2코드
203                           분류코드_연령교육정도별3코드
204                           분류코드_연령교육정도별4코드
205                           분류코드_연령교육정도별5코드
206                           분류코드_연령교육정도별6코드
207                           분류코드_연령교육정도별7코드
208                             분류코드_연령성별10코드
209                             분류코드_연령성별11코드
210                              분류코드_연령성별1코드
211                              분류코드_연령성별2코드
212                              분류코드_연령성별3코드
213                              분류코드_연령성별4코드
214                              분류코드_연령성별5코드
215                              분류코드_연령성별6코드
216                              분류코드_연령성별7코드
217                              분류코드_연령성별8코드
218                              분류코드_연령성별9코드
219                            분류코드_임금근로자구분코드
220                               분류코드_자원봉사여부
221                            분류코드_자원봉사정기성여부
222                         분류코드_장애인복지카드_소유여부
223                              분류코드_점유형태1코드
224                              분류코드_점유형태2코드
225                              분류코드_종사자지위코드
226                             분류코드_주관적만족감코드
227                            분류코드_주관적소득수준코드
228                              분류코드_주택형태1코드
229                              분류코드_주택형태2코드
230                                분류코드_직업별코드
231                           분류코드_청소년교육정도1코드
232                           분류코드_청소년교육정도2코드
233                               분류코드_현금기부여부
234                            분류코드_현금기부정기성여부
235                              분류코드_혼인상태2코드
236                               분류코드_혼인상태코드
237                        사회보험료부담인식_건강보험납부여부
238                      사회보험료부담인식_건강보험부담정도코드
239                        사회보험료부담인식_고용보험납부여부
240                      사회보험료부담인식_고용보험부담정도코드
241                        사회보험료부담인식_국민연금납부여부
242                      사회보험료부담인식_국민연금부담정도코드
243                               사회장애인차별정도코드
244                         사회적관계망_가사도움요청대상유무
245                        사회적관계망_가사도움요청대상인원수
246                          사회적관계망_교류가족친척외유무
247                         사회적관계망_교류가족친척외인원수
248                           사회적관계망_교류가족친척유무
249                          사회적관계망_교류가족친척인원수
250                       사회적관계망_대화상대도움요청대상유무
251                      사회적관계망_대화상대도움요청대상인원수
252                       사회적관계망_자금차입도움요청대상유무
253                      사회적관계망_자금차입도움요청대상인원수
254                        사회적관계망변화_가족_변화정도코드
255                    사회적관계망변화_가족외친인척_변화정도코드
256                      사회적관계망변화_기타지인_변화정도코드
257                        사회적관계망변화_동료_변화정도코드
258                        사회적관계망변화_이웃_변화정도코드
259                   사회적관계망변화_종교단체구성원_변화정도코드
260                  사회적관계망변화_취미활동단체회원_변화정도코드
261                        사회적관계망변화_친구_변화정도코드
262                        생활비마련방법_본인및배우자부담코드
263                       생활비마련방법_지원자녀및친척동거여부
264                                 생활비마련방법코드
265                   생활여건변화_문화여가생활여건_코로나관련여부
266                         생활여건변화_문화여가생활여건코드
267                    생활여건변화_보건의료서비스_코로나관련여부
268                          생활여건변화_보건의료서비스코드
269                     생활여건변화_사회보장제도_코로나관련여부
270                           생활여건변화_사회보장제도코드
271                    생활여건변화_전반적생활여건_코로나관련여부
272                          생활여건변화_전반적생활여건코드
273                                  선호장례방법코드
274                                      성별코드
275                                   성취만족도코드
276                                   소득만족도코드
277                         소득변화_감소사유_코로나관련여부
278                                    소득변화코드
279                                 소비생활만족도코드
280                                  소비생활변화코드
281                                      신뢰코드
282                            신문_인터넷신문구독분야코드
283                              신문_인터넷신문구독여부
284                            신문_인터넷신문구독주기코드
285                             신문_일반신문구독분야코드
286                               신문_일반신문구독여부
287                             신문_일반신문구독주기코드
288                                여가활동_동반자코드
289                              여가활용_불만족사유코드
290                                 여가활용만족도코드
291                               여가활용불만족사유코드
292                                  여성취업견해코드
293                                  여성취업시기코드
294                            여성취업장애요인_1순위코드
295                            여성취업장애요인_2순위코드
296                            여성취업장애요인_3순위코드
297                         우선실시장애인복지사업_1순위코드
298                         우선실시장애인복지사업_2순위코드
299                         우선실시장애인복지사업_3순위코드
300                          원격수업_비효과사유_1순위코드
301                          원격수업_비효과사유_2순위코드
302                          원격수업_비효과사유_3순위코드
303                                원격수업_효과성여부
304                                    원격수업여부
305                                  유산기부의사여부
306                                일가정생활우선도코드
307                    일가정양립제도인지도_가족돌봄휴직제인지여부
308                   일가정양립제도인지도_배우자출산휴가제인지여부
309                      일가정양립제도인지도_유연근무제인지여부
310                 일가정양립제도인지도_육아기근로시간단축제인지여부
311                      일가정양립제도인지도_육아휴직제인지여부
312                     일가정양립제도인지도_직장보육지원인지여부
313                    일가정양립제도인지도_출산전후휴가제인지여부
314                                 임금근로자구분코드
315                                      자녀유무
316                               자식세대_계층이동코드
317                   자원봉사_아동청소년노인장애인재소자관련시간수
318                    자원봉사_아동청소년노인장애인재소자관련횟수
319                       자원봉사활동_교육_1회평균활동시간수
320                         자원봉사활동_교육_연간참여총횟수
321                       자원봉사활동_국가및지역행사관련시간수
322                      자원봉사활동_국가및지역행사관련주기코드
323                        자원봉사활동_국가및지역행사관련횟수
324                        자원봉사활동_국가지역행사관련시간수
325                         자원봉사활동_국가지역행사관련횟수
326                 자원봉사활동_국제협력해외봉사_1회평균활동시간수
327                   자원봉사활동_국제협력해외봉사_연간참여총횟수
328                        자원봉사활동_기타일반봉사관련시간수
329                       자원봉사활동_기타일반봉사관련주기코드
330                         자원봉사활동_기타일반봉사관련횟수
331                    자원봉사활동_농어촌봉사_1회평균활동시간수
332                      자원봉사활동_농어촌봉사_연간참여총횟수
333                     자원봉사활동_문화행사_1회평균활동시간수
334                       자원봉사활동_문화행사_연간참여총횟수
335                     자원봉사활동_보건의료_1회평균활동시간수
336                       자원봉사활동_보건의료_연간참여총횟수
337                       자원봉사활동_상담_1회평균활동시간수
338                         자원봉사활동_상담_연간참여총횟수
339                   자원봉사활동_생활편의지원_1회평균활동시간수
340                     자원봉사활동_생활편의지원_연간참여총횟수
341                 자원봉사활동_아동청소년노인장애인재소자관련시간수
342                자원봉사활동_아동청소년노인장애인재소자관련주기코드
343                  자원봉사활동_아동청소년노인장애인재소자관련횟수
344                     자원봉사활동_안전방범_1회평균활동시간수
345                       자원봉사활동_안전방범_연간참여총횟수
346                     자원봉사활동_인권공익_1회평균활동시간수
347                       자원봉사활동_인권공익_연간참여총횟수
348                          자원봉사활동_자녀교육관련시간수
349                         자원봉사활동_자녀교육관련주기코드
350                           자원봉사활동_자녀교육관련횟수
351                   자원봉사활동_재해재난응급_1회평균활동시간수
352                     자원봉사활동_재해재난응급_연간참여총횟수
353                 자원봉사활동_재해지역주민돕기및시설복구관련시간수
354                자원봉사활동_재해지역주민돕기및시설복구관련주기코드
355                  자원봉사활동_재해지역주민돕기및시설복구관련횟수
356                  자원봉사활동_재해지역주민돕기시설복구관련시간수
357                   자원봉사활동_재해지역주민돕기시설복구관련횟수
358                     자원봉사활동_주거환경_1회평균활동시간수
359                       자원봉사활동_주거환경_연간참여총횟수
360                     자원봉사활동_행정보조_1회평균활동시간수
361                       자원봉사활동_행정보조_연간참여총횟수
362                      자원봉사활동_환경보전범죄예방관련시간수
363                     자원봉사활동_환경보전범죄예방관련주기코드
364                       자원봉사활동_환경보전범죄예방관련횟수
365                     자원봉사활동_환경보호_1회평균활동시간수
366                       자원봉사활동_환경보호_연간참여총횟수
367                             자원봉사활동미참여사유코드
368                                  자원봉사활동여부
369                              자원봉사활동인지경로코드
370                               자원봉사활동정기성여부
371                             자원봉사활동정기성주기코드
372                              자원봉사활동참여사유코드
373                                  장애구분인지여부
374                                   장애인견해코드
375                               장애인관련시설견해코드
376                               장애인복지사업견해코드
377                              장애인복지카드_소유여부
378                           장애인유대관계대상_1순위코드
379                           장애인유대관계대상_2순위코드
380                           장애인유대관계대상_3순위코드
381                                 장애인유대관계여부
382                          재택근무_비효율사유_1순위코드
383                          재택근무_비효율사유_2순위코드
384                          재택근무_비효율사유_3순위코드
385                              재택근무_코로나관련여부
386                                재택근무_효율성여부
387                                    재택근무여부
388                                    재학상태코드
389                                    재학학년코드
390                          전문성활용자원봉사활동_구분코드
391                          전문성활용자원봉사활동_내용코드
392                          전문성활용자원봉사활동_참석여부
393                               전반적일자리만족도코드
394                                    점유형태코드
395                            정기기부_물품기부_주기코드
396                               정기기부_물품기부여부
397                             정기기부_물품기부주기코드
398                            정기기부_현금기부_주기코드
399                               정기기부_현금기부여부
400                             정기기부_현금기부주기코드
401                                   종사상지위코드
402                      주관적만족감_불만족사유_코로나관련여부
403                                  주관적만족감코드
404                                 주관적소득수준코드
405                              주말여가활동_동반자코드
406                            주말휴일여가활용_1순위코드
407                            주말휴일여가활용_2순위코드
408                            주말휴일여가활용_3순위코드
409                              주중여가활동_동반자코드
410                              주중여가활용_1순위코드
411                              주중여가활용_2순위코드
412                              주중여가활용_3순위코드
413                 지난1주간경제활동_비경제활동사유_코로나관련여부
414                               지난1주간경제활동여부
415                                   직업대분류코드
416                              직업선택요인_1순위코드
417                              직업선택요인_2순위코드
418                              직업선택요인_3순위코드
419                                 직장산업대분류코드
420                                참여단체_1순위코드
421                                참여단체_2순위코드
422                                참여단체_3순위코드
423                                  청년선호직장코드
424               코로나19일상생활(방역및위생활동강화)_변화견해코드
425          코로나19일상생활(방역및위생활동강화)_변화지속가능성견해코드
426          코로나19일상생활(배달및배송을통한소비활동증가)_변화견해코드
427     코로나19일상생활(배달및배송을통한소비활동증가)_변화지속가능성견해코드
428             코로나19일상생활(여가및취미생활문화발달)_변화견해코드
429        코로나19일상생활(여가및취미생활문화발달)_변화지속가능성견해코드
430                 코로나19일상생활(온라인학습확산)_변화견해코드
431            코로나19일상생활(온라인학습확산)_변화지속가능성견해코드
432                 코로나19일상생활(유연근무제확산)_변화견해코드
433            코로나19일상생활(유연근무제확산)_변화지속가능성견해코드

In [9]:
from rapidfuzz import process, fuzz

cols = compare_df["항목명"]
matches = {}
for col in cols:
    match = process.extractOne(col, cols, scorer=fuzz.ratio)
    matches[col] = match

In [10]:
# 매칭 결과 저장
results = []
for col in compare_df["항목명"]:
    match, score, _ = process.extractOne(col, delete_blink, scorer=fuzz.ratio)
    results.append([col, match, f"{score:.4f}"])

# 데이터프레임으로 변환
match_df = pd.DataFrame(results, columns=["원본컬럼(df1)", "매칭컬럼(df2)", "유사도"])

# CSV로 저장
match_df.to_csv("항목명_매칭결과.csv", index=False, encoding="utf-8-sig")

print("항목명_매칭결과.csv 파일로 저장 완료!")

항목명_매칭결과.csv 파일로 저장 완료!

In [11]:
matched_column = {
    "레저시설_스키장이용횟수": "레저시설_스키장스케이트장이용횟수",
    "레저시설이용횟수": "레저시설_이용여부",
    "문화예술스포츠관람_음악연주회횟수": "문화예술스포츠관람_음악연주회콘서트횟수", 
    "분류코드_고용안정성": "분류코드_고용안정성여부",
    "자원봉사활동_재해지역주민돕기시설복구관련횟수": "자원봉사활동_재해지역주민돕기및시설복구관련횟수",
    "자원봉사활동_재해지역주민돕기시설복구관련시간수": "자원봉사활동_재해지역주민돕기및시설복구관련주기",
    "정기기부_현금기부_주기": "정기기부_현금기부주기",
    "정기기부_물품기부_주기": "정기기부_물품기부주기",
    "자원봉사활동_환경보호_연간참여총횟수": "자원봉사활동_환경보전범죄예방관련횟수",
    "자원봉사활동_환경보호_1회평균활동시간수": "자원봉사활동_환경보전범죄예방관련시간수",
    "자원봉사활동_국가지역행사관련시간수": "자원봉사활동_국가및지역행사관련시간수",
    "자원봉사활동_국제협력해외봉사_1회평균활동시간수": "자원봉사활동_국가및지역행사관련시간수",
    "자원봉사활동_국가지역행사관련횟수": "자원봉사활동_국가및지역행사관련횟수",
    "자원봉사활동_국제협력해외봉사_연간참여총횟수": "자원봉사활동_국가및지역행사관련횟수",
    "분류코드_고용안전성": "분류코드_고용안정성여부",
    "기부내용_물품후원단체후원_물품횟수": "기부내용_물품횟수",
    "노후사회적역할기타내용": "노후사회적역할",
    "여가활용불만족사유": "여가활용_불만족사유",
    "노후희망활동_1순위": "노후희망활동"
}

In [12]:
# 특정 열에서 치환
match_df["매칭컬럼(df2)"] = match_df["매칭컬럼(df2)"].replace(matched_column)
match_df = match_df.drop(columns=["유사도"])
match_df

,원본컬럼(df1),매칭컬럼(df2)
0,가구가중값,가구가중값
1,가구소득코드,가구소득
2,가구원가중값,가구원가중값
3,가구원번호,가구원번호
4,가구일련번호,가구일련번호
5,가구주관계코드,가구주관계
6,개인적인간관계만족도코드,개인적인간관계만족도
7,거처종류코드,거처종류
8,계층의식코드,계층의식
9,고용안정성_불안사유_코로나관련여부,고용안정성_불안사유_코로나관련여부
10,고용안정성코드,고용안정성
11,과거해외여행경험여부,과거해외여행경험여부
12,교육정도코드,교육정도
13,국내관광여행_당일여행횟수,국내관광여행_당일여행횟수
14,국내관광여행_미경험사유_코로나관련여부,국내관광여행_미경험사유_코로나관련여부
15,국내관광여행_숙박여행1회평균숙박일수,국내관광여행_숙박여행1회평균숙박일수
16,국내관광여행_숙박여행횟수,국내관광여행_숙박여행횟수
17,국내관광여행경험여부,국내관광여행경험여부
18,근로여건만족도_근로시간코드,근로여건만족도_근로시간
19,근로여건만족도_근무환경코드,근로여건만족도_근무환경
20,근로여건만족도_급여코드,근로여건만족도_급여
21,근로여건만족도_복리후생코드,근로여건만족도_복리후생
22,근로여건만족도_업무코드,근로여건만족도_업무
23,근로여건만족도_인간관계코드,근로여건만족도_인간관계
24,근로여건만족도_인사관리코드,근로여건만족도_인사관리
25,근로여건만족도_일가정양립직장문화코드,근로여건만족도_일가정양립직장문화
26,근로여건만족도_장래성코드,근로여건만족도_장래성
27,근로여건만족도_전반적일자리코드,근로여건만족도_전반적일자리
28,근로여건만족도_직장내교육훈련기회코드,근로여건만족도_직장내교육훈련기회
29,근로여건만족도_직장내성희롱방지노력코드,근로여건만족도_직장내성희롱방지노력
30,근로여건만족도_직장내폭력방지노력코드,근로여건만족도_직장내폭력방지노력
31,기부내용_기타_물품횟수,기부내용_기타_물품횟수
32,기부내용_기타_현금금액,기부내용_기타_현금금액
33,기부내용_기타_현금주기코드,기부내용_기타_현금주기
34,기부내용_기타_현금횟수,기부내용_기타_현금횟수
35,기부내용_대상자직접후원_물품횟수,기부내용_대상자직접후원_물품횟수
36,기부내용_대상자직접후원_현금금액,기부내용_대상자직접후원_현금금액
37,기부내용_대상자직접후원_현금주기코드,기부내용_대상자직접후원_현금주기
38,기부내용_대상자직접후원_현금횟수,기부내용_대상자직접후원_현금횟수
39,기부내용_모금단체후원_현금금액,기부내용_모금단체후원_현금금액
40,기부내용_모금단체후원_현금주기코드,기부내용_모금단체후원_현금주기
41,기부내용_모금단체후원_현금횟수,기부내용_모금단체후원_현금횟수
42,기부내용_물품주기코드,기부내용_물품주기
43,기부내용_물품횟수,기부내용_물품횟수
44,기부내용_물품후원단체후원_물품횟수,기부내용_물품횟수
45,기부내용_언론기관후원_물품횟수,기부내용_언론기관후원_물품횟수
46,기부내용_언론기관후원_현금금액,기부내용_언론기관후원_현금금액
47,기부내용_언론기관후원_현금주기코드,기부내용_언론기관후원_현금주기
48,기부내용_언론기관후원_현금횟수,기부내용_언론기관후원_현금횟수
49,기부내용_종교단체후원_물품횟수,기부내용_종교단체후원_물품횟수
50,기부내용_종교단체후원_현금금액,기부내용_종교단체후원_현금금액
51,기부내용_종교단체후원_현금주기코드,기부내용_종교단체후원_현금주기
52,기부내용_종교단체후원_현금횟수,기부내용_종교단체후원_현금횟수
53,기부내용_직장기업후원_물품횟수,기부내용_직장기업후원_물품횟수
54,기부내용_직장기업후원_현금금액,기부내용_직장기업후원_현금금액
55,기부내용_직장기업후원_현금주기코드,기부내용_직장기업후원_현금주기
56,기부내용_직장기업후원_현금횟수,기부내용_직장기업후원_현금횟수
57,기부대상인지경로코드,기부대상인지경로
58,기부문화확산_1순위코드,기부문화확산_1순위
59,기부문화확산_2순위코드,기부문화확산_2순위
60,기부문화확산_3순위코드,기부문화확산_3순위
61,기부사유코드,기부사유
62,기부여부,기부여부
63,기부종류코드,기부종류
64,기부희망분야_1순위코드,기부희망분야_1순위
65,기부희망분야_2순위코드,기부희망분야_2순위
66,기부희망분야_3순위코드,기부희망분야_3순위
67,긴축소비지출항목_1순위코드,긴축소비지출항목_1순위
68,긴축소비지출항목_2순위코드,긴축소비지출항목_2순위
69,긴축소비지출항목_3순위코드,긴축소비지출항목_3순위
70,내년가구재정상태코드,내년가구재정상태
71,노후사회적관심사코드,노후사회적관심사
72,노후사회적역할기타내용,노후사회적역할
73,노후사회적역할코드,노후사회적역할
74,노후생활주요활동_1순위코드,노후생활주요활동_1순위
75,노후생활주요활동_2순위코드,노후생활주요활동_2순위
76,노후생활주요활동_3순위코드,노후생활주요활동_3순위
77,노후준비방법_노후미준비사유코드,노후준비방법_노후미준비사유
78,노후준비방법_본인노후준비여부,노후준비방법_본인노후준비여부
79,노후준비방법_부수적방법코드,노후준비방법_부수적방법
80,노후준비방법_주된방법코드,노후준비방법_주된방법
81,노후희망활동_1순위코드,노후희망활동
82,노후희망활동_2순위코드,노후희망활동_2순위
83,노후희망활동_3순위코드,노후희망활동_3순위
84,노후희망활동코드,노후희망활동
85,다문화가족여부,다문화가족여부
86,단체참여_기타_코로나관련여부,단체참여_기타_코로나관련여부
87,단체참여_기타여부,단체참여_기타여부
88,단체참여_시민사회단체_코로나관련여부,단체참여_시민사회단체_코로나관련여부
89,단체참여_시민사회단체여부,단체참여_시민사회단체여부
90,단체참여_이익단체_코로나관련여부,단체참여_이익단체_코로나관련여부
91,단체참여_이익단체여부,단체참여_이익단체여부
92,단체참여_정치단체_코로나관련여부,단체참여_정치단체_코로나관련여부
93,단체참여_정치단체여부,단체참여_정치단체여부
94,단체참여_종교단체_코로나관련여부,단체참여_종교단체_코로나관련여부
95,단체참여_종교단체여부,단체참여_종교단체여부
96,단체참여_지역사회모임_코로나관련여부,단체참여_지역사회모임_코로나관련여부
97,단체참여_지역사회모임여부,단체참여_지역사회모임여부
98,단체참여_취미스포츠여가활동단체_코로나관련여부,단체참여_취미스포츠여가활동단체_코로나관련여부
99,단체참여_취미스포츠여가활동단체여부,단체참여_취미스포츠여가활동단체여부
100,단체참여_친목사교단체_코로나관련여부,단체참여_친목사교단체_코로나관련여부
101,단체참여_친목사교단체여부,단체참여_친목사교단체여부
102,단체참여_학술단체_코로나관련여부,단체참여_학술단체_코로나관련여부
103,단체참여_학술단체여부,단체참여_학술단체여부
104,단체참여여부,단체참여여부
105,독서_교양서적_전자책권수,독서_교양서적_전자책권수
106,독서_교양서적_종이책권수,독서_교양서적_종이책권수
107,독서_교양서적권수,독서_교양서적권수
108,독서_기타_오디오북권수,독서_기타_오디오북권수
109,독서_기타_전자책권수,독서_기타_전자책권수
110,독서_기타_종이책권수,독서_기타_종이책권수
111,독서_기타권수,독서_기타권수
112,독서_생활취미정보서적_오디오북권수,독서_생활취미정보서적_오디오북권수
113,독서_생활취미정보서적_전자책권수,독서_생활취미정보서적_전자책권수
114,독서_생활취미정보서적_종이책권수,독서_생활취미정보서적_종이책권수
115,독서_생활취미정보서적권수,독서_생활취미정보서적권수
116,독서_오디오북_교양서적권수,독서_오디오북_교양서적권수
117,독서_잡지류_오디오북권수,독서_잡지류_오디오북권수
118,독서_잡지류_전자책권수,독서_잡지류_전자책권수
119,독서_잡지류_종이책권수,독서_잡지류_종이책권수
120,독서_잡지류권수,독서_잡지류권수
121,독서_직업직무관련서적_오디오북권수,독서_직업직무관련서적_오디오북권수
122,독서_직업직무관련서적_전자책권수,독서_직업직무관련서적_전자책권수
123,독서_직업직무관련서적_종이책권수,독서_직업직무관련서적_종이책권수
124,독서_직업직무관련서적권수,독서_직업직무관련서적권수
125,독서여부,독서여부
126,레저시설_골프장이용횟수,레저시설_골프장이용횟수
127,레저시설_관광명소유적지국립공원이용횟수,레저시설_관광명소유적지국립공원이용횟수
128,레저시설_기타이용횟수,레저시설_기타이용횟수
129,레저시설_놀이공원이용횟수,레저시설_놀이공원이용횟수
130,레저시설_산림욕장휴양림이용횟수,레저시설_산림욕장휴양림이용횟수
131,레저시설_수영장워터파크포함이용횟수,레저시설_수영장워터파크포함이용횟수
132,레저시설_스키장스케이트장이용횟수,레저시설_스키장스케이트장이용횟수
133,레저시설_스키장이용횟수,레저시설_스키장스케이트장이용횟수
134,레저시설_온천장스파이용횟수,레저시설_온천장스파이용횟수
135,레저시설_이용여부코드,레저시설_이용여부
136,레저시설_해수욕장이용횟수,레저시설_해수욕장이용횟수
137,레저시설이용횟수,레저시설_이용여부
138,만연령,만연령
139,문화예술스포츠관람_기타횟수,문화예술스포츠관람_기타횟수
140,문화예술스포츠관람_무용_온라인횟수,문화예술스포츠관람_무용_온라인횟수
141,문화예술스포츠관람_무용횟수,문화예술스포츠관람_무용횟수
142,문화예술스포츠관람_문학행사(시화전도서전시회)_관람횟수,문화예술스포츠관람_문학행사(시화전도서전시회)_관람횟수
143,문화예술스포츠관람_미술관_온라인횟수,문화예술스포츠관람_미술관_온라인횟수
144,문화예술스포츠관람_미술관횟수,문화예술스포츠관람_미술관횟수
145,문화예술스포츠관람_박물관_온라인횟수,문화예술스포츠관람_박물관_온라인횟수
146,문화예술스포츠관람_박물관횟수,문화예술스포츠관람_박물관횟수
147,문화예술스포츠관람_스포츠횟수,문화예술스포츠관람_스포츠횟수
148,문화예술스포츠관람_연극마당극뮤지컬_온라인횟수,문화예술스포츠관람_연극마당극뮤지컬_온라인횟수
149,문화예술스포츠관람_연극마당극뮤지컬횟수,문화예술스포츠관람_연극마당극뮤지컬횟수
150,문화예술스포츠관람_영화횟수,문화예술스포츠관람_영화횟수
151,문화예술스포츠관람_음악연주회콘서트_온라인횟수,문화예술스포츠관람_음악연주회콘서트_온라인횟수
152,문화예술스포츠관람_음악연주회콘서트횟수,문화예술스포츠관람_음악연주회콘서트횟수
153,문화예술스포츠관람_음악연주회횟수,문화예술스포츠관람_음악연주회콘서트횟수
154,문화예술스포츠관람여부,문화예술스포츠관람여부
155,미기부사유코드,미기부사유
156,배우자지난1주간경제활동여부,배우자지난1주간경제활동여부
157,본인방역수칙준수코드,본인방역수칙준수
158,본인세대_계층이동코드,본인세대_계층이동
159,부채변화_증가사유_코로나관련여부,부채변화_증가사유_코로나관련여부
160,부채변화코드,부채변화
161,분류코드_가구소득1코드,분류코드_가구소득1
162,분류코드_가구소득2코드,분류코드_가구소득2
163,분류코드_가구소득3코드,분류코드_가구소득3
164,분류코드_가구원수,분류코드_가구원수
165,분류코드_가구원수2코드,분류코드_가구원수2
166,분류코드_경제활동2여부,분류코드_경제활동2여부
167,분류코드_경제활동여부,분류코드_경제활동여부
168,분류코드_계층의식코드,분류코드_계층의식
169,분류코드_고용안전성코드,분류코드_고용안정성여부
170,분류코드_고용안정성여부,분류코드_고용안정성여부
171,분류코드_교육정도코드,분류코드_교육정도
172,분류코드_기부여부,분류코드_기부여부
173,분류코드_다문화가족여부,분류코드_다문화가족여부
174,분류코드_동부읍면부구분코드,분류코드_동부읍면부구분
175,분류코드_만13세이상여부,분류코드_만13세이상여부
176,분류코드_만15세이상여부,분류코드_만15세이상여부
177,분류코드_맞벌이1여부,분류코드_맞벌이1여부
178,분류코드_맞벌이2여부,분류코드_맞벌이2여부
179,분류코드_물품기부여부,분류코드_물품기부여부
180,분류코드_물품기부정기성여부,분류코드_물품기부정기성여부
181,분류코드_산업별코드,분류코드_산업별
182,분류코드_성별코드,분류코드_성별
183,분류코드_세대구분코드,분류코드_세대구분
184,분류코드_소득만족도코드,분류코드_소득만족도
185,분류코드_연령10코드,분류코드_연령10
186,분류코드_연령11코드,분류코드_연령11
187,분류코드_연령12코드,분류코드_연령12
188,분류코드_연령13코드,분류코드_연령13
189,분류코드_연령14코드,분류코드_연령14
190,분류코드_연령15코드,분류코드_연령15
191,분류코드_연령16코드,분류코드_연령16
192,분류코드_연령1코드,분류코드_연령1
193,분류코드_연령2코드,분류코드_연령2
194,분류코드_연령3코드,분류코드_연령3
195,분류코드_연령4코드,분류코드_연령4
196,분류코드_연령5코드,분류코드_연령5
197,분류코드_연령6코드,분류코드_연령6
198,분류코드_연령7코드,분류코드_연령7
199,분류코드_연령8코드,분류코드_연령8
200,분류코드_연령9코드,분류코드_연령9
201,분류코드_연령교육정도별1코드,분류코드_연령교육정도별1
202,분류코드_연령교육정도별2코드,분류코드_연령교육정도별2
203,분류코드_연령교육정도별3코드,분류코드_연령교육정도별3
204,분류코드_연령교육정도별4코드,분류코드_연령교육정도별4
205,분류코드_연령교육정도별5코드,분류코드_연령교육정도별5
206,분류코드_연령교육정도별6코드,분류코드_연령교육정도별6
207,분류코드_연령교육정도별7코드,분류코드_연령교육정도별7
208,분류코드_연령성별10코드,분류코드_연령성별10
209,분류코드_연령성별11코드,분류코드_연령성별11
210,분류코드_연령성별1코드,분류코드_연령성별1
211,분류코드_연령성별2코드,분류코드_연령성별2
212,분류코드_연령성별3코드,분류코드_연령성별3
213,분류코드_연령성별4코드,분류코드_연령성별4
214,분류코드_연령성별5코드,분류코드_연령성별5
215,분류코드_연령성별6코드,분류코드_연령성별6
216,분류코드_연령성별7코드,분류코드_연령성별7
217,분류코드_연령성별8코드,분류코드_연령성별8
218,분류코드_연령성별9코드,분류코드_연령성별9
219,분류코드_임금근로자구분코드,분류코드_임금근로자구분
220,분류코드_자원봉사여부,분류코드_자원봉사여부
221,분류코드_자원봉사정기성여부,분류코드_자원봉사정기성여부
222,분류코드_장애인복지카드_소유여부,분류코드_장애인복지카드_소유여부
223,분류코드_점유형태1코드,분류코드_점유형태1
224,분류코드_점유형태2코드,분류코드_점유형태2
225,분류코드_종사자지위코드,분류코드_종사자지위
226,분류코드_주관적만족감코드,분류코드_주관적만족감
227,분류코드_주관적소득수준코드,분류코드_주관적소득수준
228,분류코드_주택형태1코드,분류코드_주택형태1
229,분류코드_주택형태2코드,분류코드_주택형태2
230,분류코드_직업별코드,분류코드_직업별
231,분류코드_청소년교육정도1코드,분류코드_청소년교육정도1
232,분류코드_청소년교육정도2코드,분류코드_청소년교육정도2
233,분류코드_현금기부여부,분류코드_현금기부여부
234,분류코드_현금기부정기성여부,분류코드_현금기부정기성여부
235,분류코드_혼인상태2코드,분류코드_혼인상태2
236,분류코드_혼인상태코드,분류코드_혼인상태
237,사회보험료부담인식_건강보험납부여부,사회보험료부담인식_건강보험납부여부
238,사회보험료부담인식_건강보험부담정도코드,사회보험료부담인식_건강보험부담정도
239,사회보험료부담인식_고용보험납부여부,사회보험료부담인식_고용보험납부여부
240,사회보험료부담인식_고용보험부담정도코드,사회보험료부담인식_고용보험부담정도
241,사회보험료부담인식_국민연금납부여부,사회보험료부담인식_국민연금납부여부
242,사회보험료부담인식_국민연금부담정도코드,사회보험료부담인식_국민연금부담정도
243,사회장애인차별정도코드,사회장애인차별정도
244,사회적관계망_가사도움요청대상유무,사회적관계망_가사도움요청대상유무
245,사회적관계망_가사도움요청대상인원수,사회적관계망_가사도움요청대상인원수
246,사회적관계망_교류가족친척외유무,사회적관계망_교류가족친척외유무
247,사회적관계망_교류가족친척외인원수,사회적관계망_교류가족친척외인원수
248,사회적관계망_교류가족친척유무,사회적관계망_교류가족친척유무
249,사회적관계망_교류가족친척인원수,사회적관계망_교류가족친척인원수
250,사회적관계망_대화상대도움요청대상유무,사회적관계망_대화상대도움요청대상유무
251,사회적관계망_대화상대도움요청대상인원수,사회적관계망_대화상대도움요청대상인원수
252,사회적관계망_자금차입도움요청대상유무,사회적관계망_자금차입도움요청대상유무
253,사회적관계망_자금차입도움요청대상인원수,사회적관계망_자금차입도움요청대상인원수
254,사회적관계망변화_가족_변화정도코드,사회적관계망변화_가족_변화정도
255,사회적관계망변화_가족외친인척_변화정도코드,사회적관계망변화_가족외친인척_변화정도
256,사회적관계망변화_기타지인_변화정도코드,사회적관계망변화_기타지인_변화정도
257,사회적관계망변화_동료_변화정도코드,사회적관계망변화_동료_변화정도
258,사회적관계망변화_이웃_변화정도코드,사회적관계망변화_이웃_변화정도
259,사회적관계망변화_종교단체구성원_변화정도코드,사회적관계망변화_종교단체구성원_변화정도
260,사회적관계망변화_취미활동단체회원_변화정도코드,사회적관계망변화_취미활동단체회원_변화정도
261,사회적관계망변화_친구_변화정도코드,사회적관계망변화_친구_변화정도
262,생활비마련방법_본인및배우자부담코드,생활비마련방법_본인및배우자부담
263,생활비마련방법_지원자녀및친척동거여부,생활비마련방법_지원자녀및친척동거여부
264,생활비마련방법코드,생활비마련방법
265,생활여건변화_문화여가생활여건_코로나관련여부,생활여건변화_문화여가생활여건_코로나관련여부
266,생활여건변화_문화여가생활여건코드,생활여건변화_문화여가생활여건
267,생활여건변화_보건의료서비스_코로나관련여부,생활여건변화_보건의료서비스_코로나관련여부
268,생활여건변화_보건의료서비스코드,생활여건변화_보건의료서비스
269,생활여건변화_사회보장제도_코로나관련여부,생활여건변화_사회보장제도_코로나관련여부
270,생활여건변화_사회보장제도코드,생활여건변화_사회보장제도
271,생활여건변화_전반적생활여건_코로나관련여부,생활여건변화_전반적생활여건_코로나관련여부
272,생활여건변화_전반적생활여건코드,생활여건변화_전반적생활여건
273,선호장례방법코드,선호장례방법
274,성별코드,성별
275,성취만족도코드,성취만족도
276,소득만족도코드,소득만족도
277,소득변화_감소사유_코로나관련여부,소득변화_감소사유_코로나관련여부
278,소득변화코드,소득변화
279,소비생활만족도코드,소비생활만족도
280,소비생활변화코드,소비생활변화
281,신뢰코드,신뢰
282,신문_인터넷신문구독분야코드,신문_인터넷신문구독분야
283,신문_인터넷신문구독여부,신문_인터넷신문구독여부
284,신문_인터넷신문구독주기코드,신문_인터넷신문구독주기
285,신문_일반신문구독분야코드,신문_일반신문구독분야
286,신문_일반신문구독여부,신문_일반신문구독여부
287,신문_일반신문구독주기코드,신문_일반신문구독주기
288,여가활동_동반자코드,여가활동_동반자
289,여가활용_불만족사유코드,여가활용_불만족사유
290,여가활용만족도코드,여가활용만족도
291,여가활용불만족사유코드,여가활용_불만족사유
292,여성취업견해코드,여성취업견해
293,여성취업시기코드,여성취업시기
294,여성취업장애요인_1순위코드,여성취업장애요인_1순위
295,여성취업장애요인_2순위코드,여성취업장애요인_2순위
296,여성취업장애요인_3순위코드,여성취업장애요인_3순위
297,우선실시장애인복지사업_1순위코드,우선실시장애인복지사업_1순위
298,우선실시장애인복지사업_2순위코드,우선실시장애인복지사업_2순위
299,우선실시장애인복지사업_3순위코드,우선실시장애인복지사업_3순위
300,원격수업_비효과사유_1순위코드,원격수업_비효과사유_1순위
301,원격수업_비효과사유_2순위코드,원격수업_비효과사유_2순위
302,원격수업_비효과사유_3순위코드,원격수업_비효과사유_3순위
303,원격수업_효과성여부,원격수업_효과성여부
304,원격수업여부,원격수업여부
305,유산기부의사여부,유산기부의사여부
306,일가정생활우선도코드,일가정생활우선도
307,일가정양립제도인지도_가족돌봄휴직제인지여부,일가정양립제도인지도_가족돌봄휴직제인지여부
308,일가정양립제도인지도_배우자출산휴가제인지여부,일가정양립제도인지도_배우자출산휴가제인지여부
309,일가정양립제도인지도_유연근무제인지여부,일가정양립제도인지도_유연근무제인지여부
310,일가정양립제도인지도_육아기근로시간단축제인지여부,일가정양립제도인지도_육아기근로시간단축제인지여부
311,일가정양립제도인지도_육아휴직제인지여부,일가정양립제도인지도_육아휴직제인지여부
312,일가정양립제도인지도_직장보육지원인지여부,일가정양립제도인지도_직장보육지원인지여부
313,일가정양립제도인지도_출산전후휴가제인지여부,일가정양립제도인지도_출산전후휴가제인지여부
314,임금근로자구분코드,임금근로자구분
315,자녀유무,자녀유무
316,자식세대_계층이동코드,자식세대_계층이동
317,자원봉사_아동청소년노인장애인재소자관련시간수,자원봉사_아동청소년노인장애인재소자관련시간수
318,자원봉사_아동청소년노인장애인재소자관련횟수,자원봉사_아동청소년노인장애인재소자관련횟수
319,자원봉사활동_교육_1회평균활동시간수,자원봉사활동_교육_1회평균활동시간수
320,자원봉사활동_교육_연간참여총횟수,자원봉사활동_교육_연간참여총횟수
321,자원봉사활동_국가및지역행사관련시간수,자원봉사활동_국가및지역행사관련시간수
322,자원봉사활동_국가및지역행사관련주기코드,자원봉사활동_국가및지역행사관련주기
323,자원봉사활동_국가및지역행사관련횟수,자원봉사활동_국가및지역행사관련횟수
324,자원봉사활동_국가지역행사관련시간수,자원봉사활동_국가및지역행사관련시간수
325,자원봉사활동_국가지역행사관련횟수,자원봉사활동_국가및지역행사관련횟수
326,자원봉사활동_국제협력해외봉사_1회평균활동시간수,자원봉사활동_국가및지역행사관련시간수
327,자원봉사활동_국제협력해외봉사_연간참여총횟수,자원봉사활동_국가및지역행사관련횟수
328,자원봉사활동_기타일반봉사관련시간수,자원봉사활동_기타일반봉사관련시간수
329,자원봉사활동_기타일반봉사관련주기코드,자원봉사활동_기타일반봉사관련주기
330,자원봉사활동_기타일반봉사관련횟수,자원봉사활동_기타일반봉사관련횟수
331,자원봉사활동_농어촌봉사_1회평균활동시간수,자원봉사활동_농어촌봉사_1회평균활동시간수
332,자원봉사활동_농어촌봉사_연간참여총횟수,자원봉사활동_농어촌봉사_연간참여총횟수
333,자원봉사활동_문화행사_1회평균활동시간수,자원봉사활동_문화행사_1회평균활동시간수
334,자원봉사활동_문화행사_연간참여총횟수,자원봉사활동_문화행사_연간참여총횟수
335,자원봉사활동_보건의료_1회평균활동시간수,자원봉사활동_보건의료_1회평균활동시간수
336,자원봉사활동_보건의료_연간참여총횟수,자원봉사활동_보건의료_연간참여총횟수
337,자원봉사활동_상담_1회평균활동시간수,자원봉사활동_상담_1회평균활동시간수
338,자원봉사활동_상담_연간참여총횟수,자원봉사활동_상담_연간참여총횟수
339,자원봉사활동_생활편의지원_1회평균활동시간수,자원봉사활동_생활편의지원_1회평균활동시간수
340,자원봉사활동_생활편의지원_연간참여총횟수,자원봉사활동_생활편의지원_연간참여총횟수
341,자원봉사활동_아동청소년노인장애인재소자관련시간수,자원봉사활동_아동청소년노인장애인재소자관련시간수
342,자원봉사활동_아동청소년노인장애인재소자관련주기코드,자원봉사활동_아동청소년노인장애인재소자관련주기
343,자원봉사활동_아동청소년노인장애인재소자관련횟수,자원봉사활동_아동청소년노인장애인재소자관련횟수
344,자원봉사활동_안전방범_1회평균활동시간수,자원봉사활동_안전방범_1회평균활동시간수
345,자원봉사활동_안전방범_연간참여총횟수,자원봉사활동_안전방범_연간참여총횟수
346,자원봉사활동_인권공익_1회평균활동시간수,자원봉사활동_인권공익_1회평균활동시간수
347,자원봉사활동_인권공익_연간참여총횟수,자원봉사활동_인권공익_연간참여총횟수
348,자원봉사활동_자녀교육관련시간수,자원봉사활동_자녀교육관련시간수
349,자원봉사활동_자녀교육관련주기코드,자원봉사활동_자녀교육관련주기
350,자원봉사활동_자녀교육관련횟수,자원봉사활동_자녀교육관련횟수
351,자원봉사활동_재해재난응급_1회평균활동시간수,자원봉사활동_재해재난응급_1회평균활동시간수
352,자원봉사활동_재해재난응급_연간참여총횟수,자원봉사활동_재해재난응급_연간참여총횟수
353,자원봉사활동_재해지역주민돕기및시설복구관련시간수,자원봉사활동_재해지역주민돕기및시설복구관련시간수
354,자원봉사활동_재해지역주민돕기및시설복구관련주기코드,자원봉사활동_재해지역주민돕기및시설복구관련주기
355,자원봉사활동_재해지역주민돕기및시설복구관련횟수,자원봉사활동_재해지역주민돕기및시설복구관련횟수
356,자원봉사활동_재해지역주민돕기시설복구관련시간수,자원봉사활동_재해지역주민돕기및시설복구관련주기
357,자원봉사활동_재해지역주민돕기시설복구관련횟수,자원봉사활동_재해지역주민돕기및시설복구관련횟수
358,자원봉사활동_주거환경_1회평균활동시간수,자원봉사활동_주거환경_1회평균활동시간수
359,자원봉사활동_주거환경_연간참여총횟수,자원봉사활동_주거환경_연간참여총횟수
360,자원봉사활동_행정보조_1회평균활동시간수,자원봉사활동_행정보조_1회평균활동시간수
361,자원봉사활동_행정보조_연간참여총횟수,자원봉사활동_행정보조_연간참여총횟수
362,자원봉사활동_환경보전범죄예방관련시간수,자원봉사활동_환경보전범죄예방관련시간수
363,자원봉사활동_환경보전범죄예방관련주기코드,자원봉사활동_환경보전범죄예방관련주기
364,자원봉사활동_환경보전범죄예방관련횟수,자원봉사활동_환경보전범죄예방관련횟수
365,자원봉사활동_환경보호_1회평균활동시간수,자원봉사활동_환경보전범죄예방관련시간수
366,자원봉사활동_환경보호_연간참여총횟수,자원봉사활동_환경보전범죄예방관련횟수
367,자원봉사활동미참여사유코드,자원봉사활동미참여사유
368,자원봉사활동여부,자원봉사활동여부
369,자원봉사활동인지경로코드,자원봉사활동인지경로
370,자원봉사활동정기성여부,자원봉사활동정기성여부
371,자원봉사활동정기성주기코드,자원봉사활동정기성주기
372,자원봉사활동참여사유코드,자원봉사활동참여사유
373,장애구분인지여부,장애구분인지여부
374,장애인견해코드,장애인견해
375,장애인관련시설견해코드,장애인관련시설견해
376,장애인복지사업견해코드,장애인복지사업견해
377,장애인복지카드_소유여부,장애인복지카드_소유여부
378,장애인유대관계대상_1순위코드,장애인유대관계대상_1순위
379,장애인유대관계대상_2순위코드,장애인유대관계대상_2순위
380,장애인유대관계대상_3순위코드,장애인유대관계대상_3순위
381,장애인유대관계여부,장애인유대관계여부
382,재택근무_비효율사유_1순위코드,재택근무_비효율사유_1순위
383,재택근무_비효율사유_2순위코드,재택근무_비효율사유_2순위
384,재택근무_비효율사유_3순위코드,재택근무_비효율사유_3순위
385,재택근무_코로나관련여부,재택근무_코로나관련여부
386,재택근무_효율성여부,재택근무_효율성여부
387,재택근무여부,재택근무여부
388,재학상태코드,재학상태
389,재학학년코드,재학학년
390,전문성활용자원봉사활동_구분코드,전문성활용자원봉사활동_구분
391,전문성활용자원봉사활동_내용코드,전문성활용자원봉사활동_내용
392,전문성활용자원봉사활동_참석여부,전문성활용자원봉사활동_참석여부
393,전반적일자리만족도코드,전반적일자리만족도
394,점유형태코드,점유형태
395,정기기부_물품기부_주기코드,정기기부_물품기부주기
396,정기기부_물품기부여부,정기기부_물품기부여부
397,정기기부_물품기부주기코드,정기기부_물품기부주기
398,정기기부_현금기부_주기코드,정기기부_현금기부주기
399,정기기부_현금기부여부,정기기부_현금기부여부
400,정기기부_현금기부주기코드,정기기부_현금기부주기
401,종사상지위코드,종사상지위
402,주관적만족감_불만족사유_코로나관련여부,주관적만족감_불만족사유_코로나관련여부
403,주관적만족감코드,주관적만족감
404,주관적소득수준코드,주관적소득수준
405,주말여가활동_동반자코드,주말여가활동_동반자
406,주말휴일여가활용_1순위코드,주말휴일여가활용_1순위
407,주말휴일여가활용_2순위코드,주말휴일여가활용_2순위
408,주말휴일여가활용_3순위코드,주말휴일여가활용_3순위
409,주중여가활동_동반자코드,주중여가활동_동반자
410,주중여가활용_1순위코드,주중여가활용_1순위
411,주중여가활용_2순위코드,주중여가활용_2순위
412,주중여가활용_3순위코드,주중여가활용_3순위
413,지난1주간경제활동_비경제활동사유_코로나관련여부,지난1주간경제활동_비경제활동사유_코로나관련여부
414,지난1주간경제활동여부,지난1주간경제활동여부
415,직업대분류코드,직업대분류
416,직업선택요인_1순위코드,직업선택요인_1순위
417,직업선택요인_2순위코드,직업선택요인_2순위
418,직업선택요인_3순위코드,직업선택요인_3순위
419,직장산업대분류코드,직장산업대분류
420,참여단체_1순위코드,참여단체_1순위
421,참여단체_2순위코드,참여단체_2순위
422,참여단체_3순위코드,참여단체_3순위
423,청년선호직장코드,청년선호직장
424,코로나19일상생활(방역및위생활동강화)_변화견해코드,코로나19일상생활(방역및위생활동강화)_변화견해
425,코로나19일상생활(방역및위생활동강화)_변화지속가능성견해코드,코로나19일상생활(방역및위생활동강화)_변화지속가능성견해
426,코로나19일상생활(배달및배송을통한소비활동증가)_변화견해코드,코로나19일상생활(배달및배송을통한소비활동증가)_변화견해
427,코로나19일상생활(배달및배송을통한소비활동증가)_변화지속가능성견해코드,코로나19일상생활(배달및배송을통한소비활동증가)_변화지속가능성견해
428,코로나19일상생활(여가및취미생활문화발달)_변화견해코드,코로나19일상생활(여가및취미생활문화발달)_변화견해
429,코로나19일상생활(여가및취미생활문화발달)_변화지속가능성견해코드,코로나19일상생활(여가및취미생활문화발달)_변화지속가능성견해
430,코로나19일상생활(온라인학습확산)_변화견해코드,코로나19일상생활(온라인학습확산)_변화견해
431,코로나19일상생활(온라인학습확산)_변화지속가능성견해코드,코로나19일상생활(온라인학습확산)_변화지속가능성견해
432,코로나19일상생활(유연근무제확산)_변화견해코드,코로나19일상생활(유연근무제확산)_변화견해
433,코로나19일상생활(유연근무제확산)_변화지속가능성견해코드,코로나19일상생활(유연근무제확산)_변화지속가능성견해
434,코로나19일상생활(직장단체회식감소)_변화견해코드,코로나19일상생활(직장단체회식감소)_변화견해
435,코로나19일상생활(직장단체회식감소)_변화지속가능성견해코드,코로나19일상생활(직장단체회식감소)_변화지속가능성견해
436,코로나19일상생활(친목및사교목적모임감소)_변화견해코드,코로나19일상생활(친목및사교목적모임감소)_변화견해
437,코로나19일상생활(친목및사교목적모임감소)_변화지속가능성견해코드,코로나19일상생활(친목및사교목적모임감소)_변화지속가능성견해
438,타인방역수칙준수코드,타인방역수칙준수
439,표본층번호,표본층번호
440,해외여행경험_가족친지관련횟수,해외여행경험_가족친지관련횟수
441,해외여행경험_관광횟수,해외여행경험_관광횟수
442,해외여행경험_교육횟수,해외여행경험_교육횟수
443,해외여행경험_미경험사유_코로나관련여부,해외여행경험_미경험사유_코로나관련여부
444,해외여행경험_업무횟수,해외여행경험_업무횟수
445,해외여행경험여부,해외여행경험여부
446,행정구역시도코드,행정구역시도
447,향후기부의사여부,향후기부의사여부
448,향후자녀동거의향여부,향후자녀동거의향여부
449,향후자원봉사활동의사여부,향후자원봉사활동의사여부
450,향후추가대상공공시설_1순위코드,향후추가대상공공시설_1순위
451,향후추가대상공공시설_2순위코드,향후추가대상공공시설_2순위
452,향후추가대상공공시설_3순위코드,향후추가대상공공시설_3순위
453,향후추가대상복지서비스_1순위코드,향후추가대상복지서비스_1순위
454,향후추가대상복지서비스_2순위코드,향후추가대상복지서비스_2순위
455,향후추가대상복지서비스_3순위코드,향후추가대상복지서비스_3순위
456,향후희망거처코드,향후희망거처
457,향후희망여가활동_1순위코드,향후희망여가활동_1순위
458,향후희망여가활동_2순위코드,향후희망여가활동_2순위
459,향후희망여가활동_3순위코드,향후희망여가활동_3순위
460,현재소득여부,현재소득여부
461,현재자녀동거사유_1순위코드,현재자녀동거사유_1순위
462,현재자녀동거사유_2순위코드,현재자녀동거사유_2순위
463,현재자녀동거사유_3순위코드,현재자녀동거사유_3순위
464,현재자녀동거여부,현재자녀동거여부
465,현재자녀비동거사유_1순위코드,현재자녀비동거사유_1순위
466,현재자녀비동거사유_2순위코드,현재자녀비동거사유_2순위
467,현재자녀비동거사유_3순위코드,현재자녀비동거사유_3순위
468,혼인상태코드,혼인상태
469,혼인신고여부,혼인신고여부
470,활동제약상태(계단을오르는데어려움)_어려움정도코드,활동제약상태(계단을오르는데어려움)_어려움정도
471,활동제약상태(계단을오르는데어려움)_지속예상기간코드,활동제약상태(계단을오르는데어려움)_지속예상기간
472,활동제약상태(기억하거나집중하는데어려움)_어려움정도코드,활동제약상태(기억하거나집중하는데어려움)_어려움정도
473,활동제약상태(기억하거나집중하는데어려움)_지속예상기간코드,활동제약상태(기억하거나집중하는데어려움)_지속예상기간
474,활동제약상태(보청기를사용해도듣는데어려움)_어려움정도코드,활동제약상태(보청기를사용해도듣는데어려움)_어려움정도
475,활동제약상태(보청기를사용해도듣는데어려움)_지속예상기간코드,활동제약상태(보청기를사용해도듣는데어려움)_지속예상기간
476,활동제약상태(스스로자기관리활동을하는데어려움)_어려움정도코드,활동제약상태(스스로자기관리활동을하는데어려움)_어려움정도
477,활동제약상태(스스로자기관리활동을하는데어려움)_지속예상기간코드,활동제약상태(스스로자기관리활동을하는데어려움)_지속예상기간
478,활동제약상태(안경을써도보는데어려움)_어려움정도코드,활동제약상태(안경을써도보는데어려움)_어려움정도
479,활동제약상태(안경을써도보는데어려움)_지속예상기간코드,활동제약상태(안경을써도보는데어려움)_지속예상기간
480,활동제약상태(일상생활에서말을하거나듣고이해하는데어려움)_어려움정도코드,활동제약상태(일상생활에서말을하거나듣고이해하는데어려움)_어려움정도
481,활동제약상태(일상생활에서말을하거나듣고이해하는데어려움)_지속예상기간코드,활동제약상태(일상생활에서말을하거나듣고이해하는데어려움)_지속예상기간

In [13]:
# 매핑 딕셔너리 생성
mapping_dict = dict(zip(match_df["원본컬럼(df1)"], match_df["매칭컬럼(df2)"]))

# 각 데이터프레임 컬럼명 교체 (덮어쓰기 방식)
df_2015 = df_2015.rename(columns=mapping_dict)
df_2017 = df_2017.rename(columns=mapping_dict)
df_2019 = df_2019.rename(columns=mapping_dict)
df_2021 = df_2021.rename(columns=mapping_dict)
df_2023 = df_2023.rename(columns=mapping_dict)

In [16]:
df_2015['혼인상태'] = df_2015['혼인상태'].replace({3:4, 4:5})
df_2017['혼인상태'] = df_2017['혼인상태'].replace({3:6, 4:3, 5:4, 6:5})
for i in range(1,4):
  df_2021[f'향후추가대상복지서비스_{i}순위'] = df_2021[f'향후추가대상복지서비스_{i}순위'].replace({7:6, 8:9, 9:7, 10:8})
  df_2023[f'향후추가대상복지서비스_{i}순위'] = df_2023[f'향후추가대상복지서비스_{i}순위'].replace({7:6, 8:9, 9:7, 10:8})
df_2021['선호장례방법'] =  df_2021['선호장례방법'].replace({4:5, 5:4})
for i in range(1,4):
  df_2021[f'우선실시장애인복지사업_{i}순위'] = df_2021[f'우선실시장애인복지사업_{i}순위'].replace({3:2, 4:3, 5:4, 6:10, 7:5, 8:6, 9:7, 10:8, 11:9})
  df_2023[f'우선실시장애인복지사업_{i}순위'] = df_2023[f'우선실시장애인복지사업_{i}순위'].replace({3:2, 4:3, 5:4, 6:10, 7:5, 8:6, 9:7, 10:8, 11:9})
for i in range(2,4):
  df_2023[f'노후희망활동_{i}순위'] = df_2023[f'노후희망활동_{i}순위'].replace({2:7, 3:2, 4:3, 5:4, 6:5, 7:6})
df_2021['노후희망활동'] = df_2021['노후희망활동'].replace({2:7, 3:2, 4:3, 5:4, 6:5, 7:6})
for i in range(1,4):
  df_2021[f'직업선택요인_{i}순위'] = df_2021[f'직업선택요인_{i}순위'].replace({7:9, 8:7, 9:8})
for i in range(1,4):
  df_2015[f'현재자녀비동거사유_{i}순위'] = df_2015[f'현재자녀비동거사유_{i}순위'].replace({5:6, 6:5})
  df_2017[f'현재자녀비동거사유_{i}순위'] = df_2017[f'현재자녀비동거사유_{i}순위'].replace({5:6, 6:5})
df_2015['기부여부'] = df_2015['기부여부'].replace({1:1, 2:1, 3:1, 4:0})

In [17]:
# 연도별 데이터프레임을 딕셔너리에 저장
dfs = {
    "2015": df_2015,
    "2017": df_2017,
    "2019": df_2019,
    "2021": df_2021,
    "2023": df_2023
}

# CSV로 저장 (UTF-8)
for year, df in dfs.items():
    file_name = f"df_{year}.csv"
    df.to_csv(file_name, index=False, encoding="utf-8-sig")
    print(f"{file_name} 저장 완료 ✅")

df_2015.csv 저장 완료 ✅
df_2017.csv 저장 완료 ✅
df_2019.csv 저장 완료 ✅
df_2021.csv 저장 완료 ✅
df_2023.csv 저장 완료 ✅